<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>
    <groupId>ai.nomoclaw</groupId>
    <artifactId>nomoclaw</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>nomoclaw</name>
    <description>NomoClaw</description>

    <modules>
        <module>nomoclaw-agent</module>
        <module>nomoclaw-knowledge</module>
        <module>nomoclaw-develop-tool</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <langchain4j.version>1.16.3</langchain4j.version>
        <langchain4j.onnx-scoring.version>1.17.2-beta27</langchain4j.onnx-scoring.version>
        <langchain4j.skills.version>1.17.2-beta27</langchain4j.skills.version>
        <langchain4j.dashscope.version>1.17.2-beta27</langchain4j.dashscope.version>
        <mybatis-plus.version>3.5.16</mybatis-plus.version>
        <springdoc.version>3.0.3</springdoc.version>
        <swagger.annotations.version>2.2.50</swagger.annotations.version>
        <jackson.version>3.1.0</jackson.version>
        <jackson.annotations.version>2.20.1</jackson.annotations.version>
        <rocketmq-spring-boot.version>2.3.5</rocketmq-spring-boot.version>
        <lucene.version>9.12.3</lucene.version>
    </properties>
</project>
