DROP TABLE IF EXISTS llm_provider_model;
DROP TABLE IF EXISTS llm_provider_config;
DROP TABLE IF EXISTS agent_cron_job_execution;
DROP TABLE IF EXISTS agent_cron_job;
DROP TABLE IF EXISTS agent_cron_subscription;
DROP TABLE IF EXISTS agent_tip;
DROP TABLE IF EXISTS agent_skill_relation;
DROP TABLE IF EXISTS skill_definition;
DROP TABLE IF EXISTS agent_mcp_tool_relation;
DROP TABLE IF EXISTS agent_tool_relation;
DROP TABLE IF EXISTS tool_definition;
DROP TABLE IF EXISTS mcp_tool_snapshot;
DROP TABLE IF EXISTS mcp_server_definition;
DROP TABLE IF EXISTS agent_group_member;
DROP TABLE IF EXISTS agent_group_definition;
DROP TABLE IF EXISTS agent_definition;
DROP TABLE IF EXISTS system_error_log;
DROP TABLE IF EXISTS agent_event;
DROP TABLE IF EXISTS agent_step;
DROP TABLE IF EXISTS agent_message_attachment;
DROP TABLE IF EXISTS agent_message;
DROP TABLE IF EXISTS agent_conversation;
DROP TABLE IF EXISTS agent_channel_inbound_log;
DROP TABLE IF EXISTS agent_channel_session;

CREATE TABLE IF NOT EXISTS agent_group_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agent_group_uid VARCHAR(64) NOT NULL DEFAULT '',
    group_name VARCHAR(64) NOT NULL DEFAULT '',
    display_name VARCHAR(128) NOT NULL DEFAULT '',
    avatar VARCHAR(512) NOT NULL DEFAULT '',
    description VARCHAR(512) NOT NULL DEFAULT '',
    scene_tags CLOB NOT NULL,
    collaboration_mode VARCHAR(64) NOT NULL DEFAULT '',
    min_agent_count INT NOT NULL DEFAULT 2,
    max_agent_count INT NOT NULL DEFAULT 0,
    owner_agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    sort_index INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    ext_config CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (agent_group_uid),
    UNIQUE (group_name),
    INDEX idx_agent_group_definition_status (status),
    INDEX idx_agent_group_definition_sort (sort_index)
);

CREATE TABLE IF NOT EXISTS agent_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_name VARCHAR(64) NOT NULL DEFAULT '',
    display_name VARCHAR(128) NOT NULL DEFAULT '',
    avatar VARCHAR(512) NOT NULL DEFAULT '',
    description VARCHAR(512) NOT NULL DEFAULT '',
    capability_tags CLOB NOT NULL,
    prompt_profile VARCHAR(128) NOT NULL DEFAULT '',
    model_provider_id VARCHAR(64) NOT NULL DEFAULT '',
    model_id VARCHAR(128) NOT NULL DEFAULT '',
    sort_index INT NOT NULL DEFAULT 0,
    is_group_entry TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    workspace VARCHAR(1024) NOT NULL DEFAULT '',
    ext_config CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (agent_uid),
    UNIQUE (agent_name),
    INDEX idx_agent_definition_status (status)
);

CREATE TABLE IF NOT EXISTS tool_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tool_key VARCHAR(64) NOT NULL DEFAULT '',
    display_name VARCHAR(128) NOT NULL DEFAULT '',
    description VARCHAR(512) NOT NULL DEFAULT '',
    risk_level VARCHAR(16) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    config_json CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (tool_key),
    INDEX idx_tool_definition_status (status)
);

CREATE TABLE IF NOT EXISTS agent_tool_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    relation_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    tool_key VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    config_json CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (relation_uid),
    UNIQUE (agent_uid, tool_key),
    INDEX idx_agent_tool_relation_agent (agent_uid, status)
);

CREATE TABLE IF NOT EXISTS agent_mcp_tool_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    relation_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    tool_key VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    config_json CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (relation_uid),
    UNIQUE (agent_uid, tool_key),
    INDEX idx_agent_mcp_tool_relation_agent (agent_uid, status)
);

CREATE TABLE IF NOT EXISTS mcp_server_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    server_uid VARCHAR(64) NOT NULL DEFAULT '',
    server_name VARCHAR(100) NOT NULL DEFAULT '',
    transport VARCHAR(16) NOT NULL DEFAULT 'HTTP',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    timeout_seconds INT NOT NULL DEFAULT 30,
    auto_start TINYINT(1) NOT NULL DEFAULT 1,
    config_json CLOB NULL,
    last_connected_time TIMESTAMP(3) NULL,
    last_error CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (server_uid),
    UNIQUE (server_name),
    INDEX idx_mcp_server_status (status)
);

CREATE TABLE IF NOT EXISTS mcp_tool_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    snapshot_uid VARCHAR(64) NOT NULL DEFAULT '',
    server_uid VARCHAR(64) NOT NULL DEFAULT '',
    tool_key VARCHAR(64) NOT NULL DEFAULT '',
    original_tool_name VARCHAR(128) NOT NULL DEFAULT '',
    description CLOB NULL,
    input_schema_json CLOB NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    last_synced_time TIMESTAMP(3) NOT NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (snapshot_uid),
    UNIQUE (tool_key),
    UNIQUE (server_uid, original_tool_name),
    INDEX idx_mcp_tool_server (server_uid, status)
);

CREATE TABLE IF NOT EXISTS skill_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    skill_key VARCHAR(64) NOT NULL DEFAULT '',
    display_name VARCHAR(128) NOT NULL DEFAULT '',
    description VARCHAR(512) NOT NULL DEFAULT '',
    skill_path VARCHAR(512) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    config_json CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (skill_key),
    INDEX idx_skill_definition_status (status)
);

CREATE TABLE IF NOT EXISTS agent_skill_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    relation_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    skill_key VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    config_json CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (relation_uid),
    UNIQUE (agent_uid, skill_key),
    INDEX idx_agent_skill_relation_agent (agent_uid, status)
);

CREATE TABLE IF NOT EXISTS agent_group_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_group_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    member_role VARCHAR(64) NOT NULL DEFAULT '',
    responsibility VARCHAR(255) NOT NULL DEFAULT '',
    sort_index INT NOT NULL DEFAULT 0,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (member_uid),
    UNIQUE (agent_group_uid, agent_uid),
    INDEX idx_agent_group_member_group_sort (agent_group_uid, sort_index),
    INDEX idx_agent_group_member_agent (agent_uid)
);

CREATE TABLE IF NOT EXISTS agent_tip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tip_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    title VARCHAR(128) NOT NULL DEFAULT '',
    summary VARCHAR(512) NOT NULL DEFAULT '',
    source_content TEXT NOT NULL,
    source_conversation_uid VARCHAR(64) NULL DEFAULT NULL,
    source_message_uid VARCHAR(64) NULL DEFAULT NULL,
    source_time TIMESTAMP(3) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    ext_config CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (tip_uid),
    INDEX idx_agent_tip_agent (agent_uid, status, updated_time),
    INDEX idx_agent_tip_source_message (agent_uid, source_message_uid)
);

CREATE TABLE IF NOT EXISTS agent_conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_group_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    channel VARCHAR(32) NOT NULL DEFAULT 'web',
    title VARCHAR(255) NOT NULL DEFAULT '',
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (conversation_uid),
    INDEX idx_agent_conversation_group_uid (agent_group_uid),
    INDEX idx_agent_conversation_agent_uid (agent_uid)
);

CREATE TABLE IF NOT EXISTS agent_channel_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_uid VARCHAR(64) NOT NULL DEFAULT '',
    channel VARCHAR(32) NOT NULL DEFAULT '',
    tenant_id VARCHAR(128) NOT NULL DEFAULT '',
    session_key VARCHAR(255) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    reply_target VARCHAR(1024) NOT NULL DEFAULT '',
    route_metadata CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (session_uid),
    UNIQUE (channel, tenant_id, session_key),
    INDEX idx_agent_channel_session_conversation (conversation_uid)
);

CREATE TABLE IF NOT EXISTS agent_channel_inbound_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    log_uid VARCHAR(64) NOT NULL DEFAULT '',
    channel VARCHAR(32) NOT NULL DEFAULT '',
    tenant_id VARCHAR(128) NOT NULL DEFAULT '',
    session_key VARCHAR(255) NOT NULL DEFAULT '',
    external_message_id VARCHAR(255) NOT NULL DEFAULT '',
    created_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (log_uid),
    UNIQUE (channel, tenant_id, external_message_id),
    INDEX idx_agent_channel_inbound_session (channel, tenant_id, session_key)
);

CREATE TABLE IF NOT EXISTS agent_cron_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subscription_uid VARCHAR(64) NOT NULL DEFAULT '',
    job_uid VARCHAR(64) NOT NULL DEFAULT '',
    channel VARCHAR(32) NOT NULL DEFAULT '',
    target VARCHAR(256) NOT NULL DEFAULT '',
    bot_id VARCHAR(64) NOT NULL DEFAULT '',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (subscription_uid),
    UNIQUE (job_uid, channel, target, bot_id),
    INDEX idx_agent_cron_subscription_job_enabled (job_uid, enabled)
);

CREATE TABLE IF NOT EXISTS agent_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    parent_message_uid VARCHAR(64) NOT NULL DEFAULT '',
    role VARCHAR(16) NOT NULL DEFAULT '',
    content LONGTEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT '',
    provider VARCHAR(32) NOT NULL DEFAULT '',
    model_name VARCHAR(128) NOT NULL DEFAULT '',
    input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (message_uid),
    INDEX idx_agent_message_session_time (conversation_uid, created_time),
    INDEX idx_agent_message_parent (parent_message_uid),
    INDEX idx_agent_message_session_status (conversation_uid, status),
    INDEX idx_agent_message_created_time (created_time)
);

CREATE TABLE IF NOT EXISTS agent_message_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    upload_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    original_name VARCHAR(255) NOT NULL DEFAULT '',
    content_type VARCHAR(128) NOT NULL DEFAULT '',
    mime_group VARCHAR(32) NOT NULL DEFAULT '',
    file_path VARCHAR(1024) NOT NULL DEFAULT '',
    file_url VARCHAR(1024) NOT NULL DEFAULT '',
    size_bytes BIGINT NOT NULL DEFAULT 0,
    previewable TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (upload_uid),
    INDEX idx_agent_message_attachment_conversation (conversation_uid, status, created_time),
    INDEX idx_agent_message_attachment_message (message_uid, status, created_time)
);

CREATE TABLE IF NOT EXISTS agent_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    step_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    round_index INT NOT NULL DEFAULT 1,
    step_index INT NOT NULL DEFAULT 1,
    title VARCHAR(255) NOT NULL DEFAULT '',
    tool_name VARCHAR(64) NOT NULL DEFAULT '',
    tool_args CLOB NOT NULL,
    done_criteria VARCHAR(512) NOT NULL DEFAULT '',
    risk_level VARCHAR(16) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT '',
    retry_count INT NOT NULL DEFAULT 0,
    approval_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    last_error TEXT NULL,
    output_text CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (step_uid),
    INDEX idx_agent_step_message (message_uid),
    INDEX idx_agent_step_session (conversation_uid)
);

CREATE TABLE IF NOT EXISTS agent_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    step_uid VARCHAR(64) NOT NULL DEFAULT '',
    event_type VARCHAR(64) NOT NULL DEFAULT '',
    payload CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (event_uid),
    INDEX idx_agent_event_session (conversation_uid),
    INDEX idx_agent_event_message (message_uid)
);

CREATE TABLE IF NOT EXISTS system_error_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    log_uid VARCHAR(64) NOT NULL DEFAULT '',
    level VARCHAR(16) NOT NULL DEFAULT 'ERROR',
    source VARCHAR(64) NOT NULL DEFAULT '',
    code VARCHAR(128) NOT NULL DEFAULT '',
    title VARCHAR(255) NOT NULL DEFAULT '',
    message CLOB NULL,
    detail CLOB NULL,
    occurred_time TIMESTAMP(3) NOT NULL,
    created_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (log_uid),
    INDEX idx_system_error_log_time (occurred_time),
    INDEX idx_system_error_log_level_time (level, occurred_time),
    INDEX idx_system_error_log_source_time (source, occurred_time)
);

CREATE TABLE IF NOT EXISTS agent_cron_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    title VARCHAR(255) NOT NULL DEFAULT '',
    expression VARCHAR(128) NOT NULL DEFAULT '',
    timezone VARCHAR(64) NOT NULL DEFAULT '',
    task_content VARCHAR(1024) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    last_run_time TIMESTAMP(3) NULL,
    next_run_time TIMESTAMP(3) NULL,
    last_result TEXT NULL,
    ext_config CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (job_uid),
    INDEX idx_agent_cron_job_agent (agent_uid, status),
    INDEX idx_agent_cron_job_next_run (status, next_run_time)
);

CREATE TABLE IF NOT EXISTS agent_cron_job_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    execution_uid VARCHAR(64) NOT NULL DEFAULT '',
    job_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    summary VARCHAR(1024) NOT NULL DEFAULT '',
    report_path VARCHAR(1024) NOT NULL DEFAULT '',
    read_flag INT NOT NULL DEFAULT 0,
    started_time TIMESTAMP(3) NOT NULL,
    finished_time TIMESTAMP(3) NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (execution_uid),
    INDEX idx_agent_cron_job_execution_job (job_uid, started_time),
    INDEX idx_agent_cron_job_execution_status_time (status, started_time),
    INDEX idx_agent_cron_job_execution_conversation (conversation_uid)
);

INSERT INTO agent_definition (
    agent_uid, agent_name, display_name, avatar, description, capability_tags, prompt_profile,
    model_provider_id, model_id, sort_index, is_group_entry, status, workspace, ext_config, created_time, updated_time
) VALUES
    ('agent_general_assistant', 'default_agent', '默认助手', '🤝', '负责综合规划、协调执行与最终总结。', '["planning","coordination","delivery"]',
     'generalist', '', '', 10, 0, 'ACTIVE', '', '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO tool_definition (
    tool_key, display_name, description, risk_level, status, sort_index, config_json, created_time, updated_time
) VALUES
    ('CommandTool', '命令执行', 'Execute a local shell command on the current machine.', 'HIGH', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BrowserTool', '浏览器工具', 'Operate a browser page to open URLs, click, type, extract text, or take screenshots.', 'HIGH', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ReadFileTool', '文件读取', 'Read local file content by path with optional line range.', 'LOW', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ListFileTool', '目录列举', 'List direct children of a local directory by path.', 'LOW', 'ACTIVE', 41, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CreateFileTool', '文件创建/写入', 'Create or append local file content.', 'HIGH', 'ACTIVE', 42, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EditFileTool', '文件编辑', 'Edit local file by replacing oldText with newText.', 'HIGH', 'ACTIVE', 43, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('WebSearchTool', '网页搜索', 'Search the public web for recent information by query.', 'LOW', 'ACTIVE', 50, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('WebFetchTool', '网页抓取', 'Fetch a public HTTP(S) URL and return extracted text content.', 'LOW', 'ACTIVE', 51, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CronCreateTool', '创建定时任务', 'Create a scheduled cron-like automation task.', 'HIGH', 'ACTIVE', 60, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CronDeleteTool', '删除定时任务', 'Delete a scheduled cron-like automation task.', 'HIGH', 'ACTIVE', 61, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CronListTool', '查询定时任务', 'List or query scheduled cron-like automation tasks.', 'HIGH', 'ACTIVE', 62, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('FileSearchTool', '文件搜索', 'Search files by text grep or glob pattern.', 'LOW', 'ACTIVE', 70, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('GrepTool', '正则搜索', 'Search file contents with regular expressions under the current agent workspace.', 'LOW', 'ACTIVE', 71, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('DesktopScreenshotTool', '桌面截图', 'Capture a desktop screenshot on the local machine.', 'LOW', 'ACTIVE', 80, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CurrentTimeTool', '当前时间', 'Get the current UTC time.', 'LOW', 'ACTIVE', 90, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TokenUsageTool', 'Token 使用', 'Query stored token usage summary from message records.', 'LOW', 'ACTIVE', 100, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MemorySearchTool', '记忆搜索', 'Search historical conversation messages by keyword.', 'LOW', 'ACTIVE', 110, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ImageLoaderTool', '图片加载', 'On-demand image context loader for visual analysis after tools that return image paths; supports 刚才截图/第N轮截图/文件名 and direct HTTP(S) image URL passthrough without local download.', 'LOW', 'ACTIVE', 115, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO skill_definition (
    skill_key, display_name, description, skill_path, status, sort_index, config_json, created_time, updated_time
) VALUES
    ('pdf', 'pdf', 'Use this skill whenever the task involves reading or generating PDFs.', 'skills/pdf', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('xlsx', 'xlsx', 'Use this skill whenever the task involves spreadsheet files (.xlsx/.xls/.csv/.tsv).', 'skills/xlsx', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('pptx', 'pptx', 'Use this skill whenever the task involves creating or editing PowerPoint presentations.', 'skills/pptx', 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('docx', 'docx', 'Use this skill whenever the task involves creating or editing Word documents with formatting fidelity.', 'skills/docx', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO agent_tool_relation (
    relation_uid, agent_uid, tool_key, status, sort_index, config_json, created_time, updated_time
) VALUES
    ('RelGeneralCommand', 'agent_general_assistant', 'CommandTool', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralBrowser', 'agent_general_assistant', 'BrowserTool', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralReadFile', 'agent_general_assistant', 'ReadFileTool', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralListFile', 'agent_general_assistant', 'ListFileTool', 'ACTIVE', 41, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralCreateFile', 'agent_general_assistant', 'CreateFileTool', 'ACTIVE', 42, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralEditFile', 'agent_general_assistant', 'EditFileTool', 'ACTIVE', 43, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralWebSearch', 'agent_general_assistant', 'WebSearchTool', 'ACTIVE', 50, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralWebFetch', 'agent_general_assistant', 'WebFetchTool', 'ACTIVE', 51, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralCronCreate', 'agent_general_assistant', 'CronCreateTool', 'ACTIVE', 60, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralCronDelete', 'agent_general_assistant', 'CronDeleteTool', 'ACTIVE', 61, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralCronList', 'agent_general_assistant', 'CronListTool', 'ACTIVE', 62, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralSearch', 'agent_general_assistant', 'FileSearchTool', 'ACTIVE', 70, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralGrep', 'agent_general_assistant', 'GrepTool', 'ACTIVE', 71, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralShot', 'agent_general_assistant', 'DesktopScreenshotTool', 'ACTIVE', 80, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralTime', 'agent_general_assistant', 'CurrentTimeTool', 'ACTIVE', 90, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralToken', 'agent_general_assistant', 'TokenUsageTool', 'ACTIVE', 100, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralMemory', 'agent_general_assistant', 'MemorySearchTool', 'ACTIVE', 110, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RelGeneralImageLoader', 'agent_general_assistant', 'ImageLoaderTool', 'ACTIVE', 115, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO agent_skill_relation (
    relation_uid, agent_uid, skill_key, status, sort_index, config_json, created_time, updated_time
) VALUES
    ('rel_general_pdf', 'agent_general_assistant', 'pdf', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_xlsx', 'agent_general_assistant', 'xlsx', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_pptx', 'agent_general_assistant', 'pptx', 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_docx', 'agent_general_assistant', 'docx', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO agent_tip (
    tip_uid, agent_uid, title, summary, source_content, source_conversation_uid, source_message_uid,
    source_time, status, sort_index, ext_config, created_time, updated_time
) VALUES
    ('tip_general_weather_brief', 'agent_general_assistant', '天气查询汇报（示例）',
     '先查今天天气，再用 3 句话汇报：天气现状、体感建议、是否需要带伞。',
     '请查询今天北京天气，并给我一段简洁汇报：天气、温度、出行建议。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_meeting_minutes', 'agent_general_assistant', '会议纪要整理',
     '按“结论、待办、负责人、截止时间”四段输出，先结论后细节。',
     '把会议录音整理成纪要，并提取可执行待办。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_weekly_report', 'agent_general_assistant', '周报生成',
     '分成“本周完成、下周计划、风险阻塞”三块，每块不超过 3 条。',
     '根据本周工作记录，写一份简洁周报。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_resume_screening', 'agent_general_assistant', '简历初筛',
     '先给匹配分，再写风险项，最后给“推荐/备选/不推荐”的结论。',
     '请筛选候选人简历并给出推荐意见。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_competitor_analysis', 'agent_general_assistant', '竞品分析速览',
     '按“产品定位、优势、短板、可借鉴点”输出，避免长篇描述。',
     '对比三个竞品并给出结论。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 50, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_email_rewrite', 'agent_general_assistant', '商务邮件润色',
     '保持礼貌和直接，先目的后请求，最后附明确下一步。',
     '帮我把这封商务邮件改得更专业。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 60, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_sop_draft', 'agent_general_assistant', 'SOP 草案',
     '按“目标、步骤、检查项、异常处理”结构写，便于落地执行。',
     '给这个流程写一份标准操作说明。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 70, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_customer_reply', 'agent_general_assistant', '客户回复模板',
     '先共情，再给方案，最后确认时间点，控制在 120 字内。',
     '帮我回复客户投诉邮件。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 80, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_content_outline', 'agent_general_assistant', '内容大纲生成',
     '先给 5 条一级标题，再给每条 2-3 个要点，结构清晰即可。',
     '帮我写一篇文章的大纲。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 90, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_risk_checklist', 'agent_general_assistant', '风险排查清单',
     '按“高/中/低风险”分组列出，并给每项一个可执行规避建议。',
     '帮我排查这个方案的风险。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 100, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS llm_provider_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider_id VARCHAR(64) NOT NULL DEFAULT '',
    provider_name VARCHAR(128) NOT NULL DEFAULT '',
    protocol VARCHAR(64) NOT NULL DEFAULT '',
    base_url VARCHAR(512) NOT NULL DEFAULT '',
    api_key_ciphertext TEXT NOT NULL,
    default_model VARCHAR(128) NOT NULL DEFAULT '',
    local TINYINT(1) NOT NULL DEFAULT 0,
    require_api_key TINYINT(1) NOT NULL DEFAULT 1,
    freeze_url TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    ext_config CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (provider_id),
    INDEX idx_llm_provider_config_status (status)
);

CREATE TABLE IF NOT EXISTS llm_provider_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider_id VARCHAR(64) NOT NULL DEFAULT '',
    model_id VARCHAR(128) NOT NULL DEFAULT '',
    model_name VARCHAR(255) NOT NULL DEFAULT '',
    capabilities_json CLOB NOT NULL,
    reasoning TINYINT(1) NOT NULL DEFAULT 0,
    context_window INT NOT NULL DEFAULT 0,
    max_input_tokens INT NOT NULL DEFAULT 0,
    max_output_tokens INT NOT NULL DEFAULT 0,
    upload_policy_json CLOB NULL,
    sort_index INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (provider_id, model_id),
    INDEX idx_llm_provider_model_provider (provider_id, status, sort_index)
);
