DROP TABLE IF EXISTS llm_provider_model;
DROP TABLE IF EXISTS llm_provider_config;
DROP TABLE IF EXISTS agent_cron_job;
DROP TABLE IF EXISTS agent_cron_subscription;
DROP TABLE IF EXISTS agent_tip;
DROP TABLE IF EXISTS agent_skill_relation;
DROP TABLE IF EXISTS skill_definition;
DROP TABLE IF EXISTS agent_tool_relation;
DROP TABLE IF EXISTS tool_definition;
DROP TABLE IF EXISTS agent_group_member;
DROP TABLE IF EXISTS agent_group_definition;
DROP TABLE IF EXISTS agent_definition;
DROP TABLE IF EXISTS agent_event;
DROP TABLE IF EXISTS agent_step;
DROP TABLE IF EXISTS agent_message_attachment;
DROP TABLE IF EXISTS agent_message;
DROP TABLE IF EXISTS agent_conversation;
DROP TABLE IF EXISTS agent_channel_inbound_log;
DROP TABLE IF EXISTS agent_channel_session;

CREATE TABLE IF NOT EXISTS agent_group_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agent_group_uid VARCHAR(64) NOT NULL DEFAULT '',
    group_name VARCHAR(64) NOT NULL DEFAULT '',
    display_name VARCHAR(128) NOT NULL DEFAULT '',
    avatar VARCHAR(512) NOT NULL DEFAULT '',
    description VARCHAR(512) NOT NULL DEFAULT '',
    scene_tags CLOB NOT NULL,
    collaboration_mode VARCHAR(64) NOT NULL DEFAULT '',
    min_agent_count INT NOT NULL DEFAULT 2,
    max_agent_count INT NOT NULL DEFAULT 0,
    owner_agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    sort_index INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    ext_config CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (agent_group_uid),
    UNIQUE (group_name),
    INDEX idx_agent_group_definition_status (status),
    INDEX idx_agent_group_definition_sort (sort_index)
);

CREATE TABLE IF NOT EXISTS agent_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_name VARCHAR(64) NOT NULL DEFAULT '',
    display_name VARCHAR(128) NOT NULL DEFAULT '',
    avatar VARCHAR(512) NOT NULL DEFAULT '',
    description VARCHAR(512) NOT NULL DEFAULT '',
    capability_tags CLOB NOT NULL,
    prompt_profile VARCHAR(128) NOT NULL DEFAULT '',
    model_provider_id VARCHAR(64) NOT NULL DEFAULT '',
    model_id VARCHAR(128) NOT NULL DEFAULT '',
    sort_index INT NOT NULL DEFAULT 0,
    is_group_entry TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    ext_config CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (agent_uid),
    UNIQUE (agent_name),
    INDEX idx_agent_definition_status (status)
);

CREATE TABLE IF NOT EXISTS tool_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tool_key VARCHAR(64) NOT NULL DEFAULT '',
    display_name VARCHAR(128) NOT NULL DEFAULT '',
    description VARCHAR(512) NOT NULL DEFAULT '',
    risk_level VARCHAR(16) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    config_json CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (tool_key),
    INDEX idx_tool_definition_status (status)
);

CREATE TABLE IF NOT EXISTS agent_tool_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    relation_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    tool_key VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    config_json CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (relation_uid),
    UNIQUE (agent_uid, tool_key),
    INDEX idx_agent_tool_relation_agent (agent_uid, status)
);

CREATE TABLE IF NOT EXISTS skill_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    skill_key VARCHAR(64) NOT NULL DEFAULT '',
    display_name VARCHAR(128) NOT NULL DEFAULT '',
    description VARCHAR(512) NOT NULL DEFAULT '',
    skill_path VARCHAR(512) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    config_json CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (skill_key),
    INDEX idx_skill_definition_status (status)
);

CREATE TABLE IF NOT EXISTS agent_skill_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    relation_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    skill_key VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    config_json CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (relation_uid),
    UNIQUE (agent_uid, skill_key),
    INDEX idx_agent_skill_relation_agent (agent_uid, status)
);

CREATE TABLE IF NOT EXISTS agent_group_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_group_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    member_role VARCHAR(64) NOT NULL DEFAULT '',
    responsibility VARCHAR(255) NOT NULL DEFAULT '',
    sort_index INT NOT NULL DEFAULT 0,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (member_uid),
    UNIQUE (agent_group_uid, agent_uid),
    INDEX idx_agent_group_member_group_sort (agent_group_uid, sort_index),
    INDEX idx_agent_group_member_agent (agent_uid)
);

CREATE TABLE IF NOT EXISTS agent_tip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tip_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    title VARCHAR(128) NOT NULL DEFAULT '',
    summary VARCHAR(512) NOT NULL DEFAULT '',
    source_content TEXT NOT NULL,
    source_conversation_uid VARCHAR(64) NULL DEFAULT NULL,
    source_message_uid VARCHAR(64) NULL DEFAULT NULL,
    source_time TIMESTAMP(3) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    sort_index INT NOT NULL DEFAULT 0,
    ext_config CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (tip_uid),
    INDEX idx_agent_tip_agent (agent_uid, status, updated_time),
    INDEX idx_agent_tip_source_message (agent_uid, source_message_uid)
);

CREATE TABLE IF NOT EXISTS agent_conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_group_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    channel VARCHAR(32) NOT NULL DEFAULT 'web',
    title VARCHAR(255) NOT NULL DEFAULT '',
    input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (conversation_uid),
    INDEX idx_agent_conversation_group_uid (agent_group_uid),
    INDEX idx_agent_conversation_agent_uid (agent_uid)
);

CREATE TABLE IF NOT EXISTS agent_channel_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_uid VARCHAR(64) NOT NULL DEFAULT '',
    channel VARCHAR(32) NOT NULL DEFAULT '',
    tenant_id VARCHAR(128) NOT NULL DEFAULT '',
    session_key VARCHAR(255) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    reply_target VARCHAR(1024) NOT NULL DEFAULT '',
    route_metadata CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (session_uid),
    UNIQUE (channel, tenant_id, session_key),
    INDEX idx_agent_channel_session_conversation (conversation_uid)
);

CREATE TABLE IF NOT EXISTS agent_channel_inbound_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    log_uid VARCHAR(64) NOT NULL DEFAULT '',
    channel VARCHAR(32) NOT NULL DEFAULT '',
    tenant_id VARCHAR(128) NOT NULL DEFAULT '',
    session_key VARCHAR(255) NOT NULL DEFAULT '',
    external_message_id VARCHAR(255) NOT NULL DEFAULT '',
    created_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (log_uid),
    UNIQUE (channel, tenant_id, external_message_id),
    INDEX idx_agent_channel_inbound_session (channel, tenant_id, session_key)
);

CREATE TABLE IF NOT EXISTS agent_cron_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subscription_uid VARCHAR(64) NOT NULL DEFAULT '',
    job_uid VARCHAR(64) NOT NULL DEFAULT '',
    channel VARCHAR(32) NOT NULL DEFAULT '',
    target VARCHAR(256) NOT NULL DEFAULT '',
    bot_id VARCHAR(64) NOT NULL DEFAULT '',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (subscription_uid),
    UNIQUE (job_uid, channel, target, bot_id),
    INDEX idx_agent_cron_subscription_job_enabled (job_uid, enabled)
);

CREATE TABLE IF NOT EXISTS agent_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    parent_message_uid VARCHAR(64) NOT NULL DEFAULT '',
    role VARCHAR(16) NOT NULL DEFAULT '',
    content LONGTEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT '',
    provider VARCHAR(32) NOT NULL DEFAULT '',
    model_name VARCHAR(128) NOT NULL DEFAULT '',
    input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (message_uid),
    INDEX idx_agent_message_session_time (conversation_uid, created_time),
    INDEX idx_agent_message_parent (parent_message_uid),
    INDEX idx_agent_message_session_status (conversation_uid, status),
    INDEX idx_agent_message_created_time (created_time)
);

CREATE TABLE IF NOT EXISTS agent_message_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    upload_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    original_name VARCHAR(255) NOT NULL DEFAULT '',
    content_type VARCHAR(128) NOT NULL DEFAULT '',
    mime_group VARCHAR(32) NOT NULL DEFAULT '',
    file_path VARCHAR(1024) NOT NULL DEFAULT '',
    file_url VARCHAR(1024) NOT NULL DEFAULT '',
    size_bytes BIGINT NOT NULL DEFAULT 0,
    previewable TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (upload_uid),
    INDEX idx_agent_message_attachment_conversation (conversation_uid, status, created_time),
    INDEX idx_agent_message_attachment_message (message_uid, status, created_time)
);

CREATE TABLE IF NOT EXISTS agent_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    step_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    round_index INT NOT NULL DEFAULT 1,
    step_index INT NOT NULL DEFAULT 1,
    title VARCHAR(255) NOT NULL DEFAULT '',
    tool_name VARCHAR(64) NOT NULL DEFAULT '',
    tool_args CLOB NOT NULL,
    done_criteria VARCHAR(512) NOT NULL DEFAULT '',
    risk_level VARCHAR(16) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT '',
    retry_count INT NOT NULL DEFAULT 0,
    approval_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    last_error TEXT NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (step_uid),
    INDEX idx_agent_step_message (message_uid),
    INDEX idx_agent_step_session (conversation_uid)
);

CREATE TABLE IF NOT EXISTS agent_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    step_uid VARCHAR(64) NOT NULL DEFAULT '',
    event_type VARCHAR(64) NOT NULL DEFAULT '',
    payload CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (event_uid),
    INDEX idx_agent_event_session (conversation_uid),
    INDEX idx_agent_event_message (message_uid)
);

CREATE TABLE IF NOT EXISTS agent_cron_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_uid VARCHAR(64) NOT NULL DEFAULT '',
    agent_uid VARCHAR(64) NOT NULL DEFAULT '',
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    title VARCHAR(255) NOT NULL DEFAULT '',
    expression VARCHAR(128) NOT NULL DEFAULT '',
    timezone VARCHAR(64) NOT NULL DEFAULT '',
    task_content VARCHAR(1024) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    last_run_time TIMESTAMP(3) NULL,
    next_run_time TIMESTAMP(3) NULL,
    last_result TEXT NULL,
    ext_config CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (job_uid),
    INDEX idx_agent_cron_job_agent (agent_uid, status),
    INDEX idx_agent_cron_job_next_run (status, next_run_time)
);

INSERT INTO agent_group_definition (
    agent_group_uid, group_name, display_name, avatar, description, scene_tags,
    collaboration_mode, min_agent_count, max_agent_count, owner_agent_uid, sort_index, status, ext_config, created_time, updated_time
) VALUES
    ('group_short_drama', 'short_drama_team', '短剧项目组', '🎭', '面向短剧策划、测试、舆情与营销的一体化协作群组。', '["short-drama","creative","operations"]',
     'pipeline', 2, 12, 'agent_general_assistant', 10, 'ACTIVE', '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO agent_definition (
    agent_uid, agent_name, display_name, avatar, description, capability_tags, prompt_profile,
    model_provider_id, model_id, sort_index, is_group_entry, status, ext_config, created_time, updated_time
) VALUES
    ('agent_general_assistant', 'general_assistant', '通用助手', '🤝', '负责综合规划、协调执行与最终总结。', '["planning","coordination","delivery"]',
     'generalist', '', '', 10, 0, 'ACTIVE', '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('agent_test_expert', 'test_expert', '测试专家', '🧪', '负责测试设计、缺陷定位与质量把关。', '["testing","qa","review"]',
     'qa-specialist', '', '', 20, 0, 'ACTIVE', '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('agent_public_opinion', 'public_opinion_monitor', '舆情监测', '📡', '负责舆情跟踪、热点观察与风险提示。', '["monitoring","trend","risk"]',
     'opinion-specialist', '', '', 30, 0, 'ACTIVE', '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('agent_marketing_assistant', 'marketing_assistant', '营销助理', '📣', '负责传播文案、活动建议与投放辅助。', '["marketing","campaign","copywriting"]',
     'marketing-specialist', '', '', 40, 0, 'ACTIVE', '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('agent_screenwriter', 'screenwriter', '短剧编剧', '✍️', '负责短剧剧情设定、人物弧线与分场创作。', '["screenwriting","story","character"]',
     'screenwriter-specialist', '', '', 50, 0, 'ACTIVE', '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('agent_director', 'director', '短剧导演', '🎬', '负责镜头节奏、视听表达与导演层决策。', '["direction","visual","production"]',
     'director-specialist', '', '', 60, 0, 'ACTIVE', '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO tool_definition (
    tool_key, display_name, description, risk_level, status, sort_index, config_json, created_time, updated_time
) VALUES
    ('command_tool', '命令执行', 'Execute a local shell command on the current machine.', 'HIGH', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('browser_tool', '浏览器工具', 'Operate a browser page to open URLs, click, type, extract text, or take screenshots.', 'HIGH', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('browser_control_tool', '浏览器控制', 'Operate the browser with action-based controls.', 'HIGH', 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('file_tool', '文件工具', 'Read, list, or write local files.', 'HIGH', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('file_io_tool', '文件IO', 'Read, write, append, edit, or list local files.', 'HIGH', 'ACTIVE', 50, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('cron_tool', '定时任务', 'Create a scheduled cron-like automation task.', 'HIGH', 'ACTIVE', 60, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('file_search_tool', '文件搜索', 'Search files by text grep or glob pattern.', 'LOW', 'ACTIVE', 70, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('desktop_screenshot_tool', '桌面截图', 'Capture a desktop screenshot on the local machine.', 'LOW', 'ACTIVE', 80, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('current_time_tool', '当前时间', 'Get the current UTC time.', 'LOW', 'ACTIVE', 90, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('token_usage_tool', 'Token 使用', 'Query stored token usage summary from message records.', 'LOW', 'ACTIVE', 100, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('memory_search_tool', '记忆搜索', 'Search historical conversation messages by keyword.', 'LOW', 'ACTIVE', 110, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('send_file_tool', '发送文件', 'Prepare a local file for sending to the user.', 'LOW', 'ACTIVE', 120, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO skill_definition (
    skill_key, display_name, description, skill_path, status, sort_index, config_json, created_time, updated_time
) VALUES
    ('pdf', 'pdf', 'Use this skill whenever the task involves reading or generating PDFs.', 'skills/pdf', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO agent_group_member (
    member_uid, agent_group_uid, agent_uid, member_role, responsibility, sort_index, is_primary, status, created_time, updated_time
) VALUES
    ('member_short_drama_general', 'group_short_drama', 'agent_general_assistant', 'owner', '统筹项目组整体规划、协调执行与最终交付。', 10, 1, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('member_short_drama_test', 'group_short_drama', 'agent_test_expert', 'reviewer', '负责测试方案设计、缺陷校验与质量反馈。', 20, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('member_short_drama_public', 'group_short_drama', 'agent_public_opinion', 'analyst', '负责舆情监测、风险发现与热点观察。', 30, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('member_short_drama_marketing', 'group_short_drama', 'agent_marketing_assistant', 'strategist', '负责营销传播建议与活动辅助。', 40, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('member_short_drama_screenwriter', 'group_short_drama', 'agent_screenwriter', 'creator', '负责短剧剧本、人物与桥段创作。', 50, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('member_short_drama_director', 'group_short_drama', 'agent_director', 'director', '负责镜头、节奏与导演侧统筹。', 60, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO agent_tool_relation (
    relation_uid, agent_uid, tool_key, status, sort_index, config_json, created_time, updated_time
) VALUES
    ('rel_general_command', 'agent_general_assistant', 'command_tool', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_browser', 'agent_general_assistant', 'browser_tool', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_browser_control', 'agent_general_assistant', 'browser_control_tool', 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_file', 'agent_general_assistant', 'file_tool', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_file_io', 'agent_general_assistant', 'file_io_tool', 'ACTIVE', 50, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_cron', 'agent_general_assistant', 'cron_tool', 'ACTIVE', 60, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_search', 'agent_general_assistant', 'file_search_tool', 'ACTIVE', 70, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_shot', 'agent_general_assistant', 'desktop_screenshot_tool', 'ACTIVE', 80, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_time', 'agent_general_assistant', 'current_time_tool', 'ACTIVE', 90, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_token', 'agent_general_assistant', 'token_usage_tool', 'ACTIVE', 100, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_memory', 'agent_general_assistant', 'memory_search_tool', 'ACTIVE', 110, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_general_send', 'agent_general_assistant', 'send_file_tool', 'ACTIVE', 120, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_test_command', 'agent_test_expert', 'command_tool', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_test_file', 'agent_test_expert', 'file_io_tool', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_test_search', 'agent_test_expert', 'file_search_tool', 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_test_time', 'agent_test_expert', 'current_time_tool', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_test_memory', 'agent_test_expert', 'memory_search_tool', 'ACTIVE', 50, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_public_browser', 'agent_public_opinion', 'browser_tool', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_public_browser_control', 'agent_public_opinion', 'browser_control_tool', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_public_search', 'agent_public_opinion', 'file_search_tool', 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_public_time', 'agent_public_opinion', 'current_time_tool', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_public_memory', 'agent_public_opinion', 'memory_search_tool', 'ACTIVE', 50, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_market_command', 'agent_marketing_assistant', 'command_tool', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_market_browser', 'agent_marketing_assistant', 'browser_tool', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_market_search', 'agent_marketing_assistant', 'file_search_tool', 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_market_time', 'agent_marketing_assistant', 'current_time_tool', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_market_memory', 'agent_marketing_assistant', 'memory_search_tool', 'ACTIVE', 50, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_writer_command', 'agent_screenwriter', 'command_tool', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_writer_file', 'agent_screenwriter', 'file_io_tool', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_writer_time', 'agent_screenwriter', 'current_time_tool', 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_writer_memory', 'agent_screenwriter', 'memory_search_tool', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_director_command', 'agent_director', 'command_tool', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_director_browser', 'agent_director', 'browser_tool', 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_director_shot', 'agent_director', 'desktop_screenshot_tool', 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_director_time', 'agent_director', 'current_time_tool', 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO agent_skill_relation (
    relation_uid, agent_uid, skill_key, status, sort_index, config_json, created_time, updated_time
) VALUES
    ('rel_general_pdf', 'agent_general_assistant', 'pdf', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_test_pdf', 'agent_test_expert', 'pdf', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_public_pdf', 'agent_public_opinion', 'pdf', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_market_pdf', 'agent_marketing_assistant', 'pdf', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_writer_pdf', 'agent_screenwriter', 'pdf', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rel_director_pdf', 'agent_director', 'pdf', 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO agent_tip (
    tip_uid, agent_uid, title, summary, source_content, source_conversation_uid, source_message_uid,
    source_time, status, sort_index, ext_config, created_time, updated_time
) VALUES
    ('tip_general_weather_brief', 'agent_general_assistant', '天气查询汇报（示例）',
     '先查今天天气，再用 3 句话汇报：天气现状、体感建议、是否需要带伞。',
     '请查询今天北京天气，并给我一段简洁汇报：天气、温度、出行建议。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 10, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_meeting_minutes', 'agent_general_assistant', '会议纪要整理',
     '按“结论、待办、负责人、截止时间”四段输出，先结论后细节。',
     '把会议录音整理成纪要，并提取可执行待办。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 20, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_weekly_report', 'agent_general_assistant', '周报生成',
     '分成“本周完成、下周计划、风险阻塞”三块，每块不超过 3 条。',
     '根据本周工作记录，写一份简洁周报。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 30, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_resume_screening', 'agent_general_assistant', '简历初筛',
     '先给匹配分，再写风险项，最后给“推荐/备选/不推荐”的结论。',
     '请筛选候选人简历并给出推荐意见。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 40, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_competitor_analysis', 'agent_general_assistant', '竞品分析速览',
     '按“产品定位、优势、短板、可借鉴点”输出，避免长篇描述。',
     '对比三个竞品并给出结论。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 50, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_email_rewrite', 'agent_general_assistant', '商务邮件润色',
     '保持礼貌和直接，先目的后请求，最后附明确下一步。',
     '帮我把这封商务邮件改得更专业。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 60, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_sop_draft', 'agent_general_assistant', 'SOP 草案',
     '按“目标、步骤、检查项、异常处理”结构写，便于落地执行。',
     '给这个流程写一份标准操作说明。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 70, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_customer_reply', 'agent_general_assistant', '客户回复模板',
     '先共情，再给方案，最后确认时间点，控制在 120 字内。',
     '帮我回复客户投诉邮件。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 80, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_content_outline', 'agent_general_assistant', '内容大纲生成',
     '先给 5 条一级标题，再给每条 2-3 个要点，结构清晰即可。',
     '帮我写一篇文章的大纲。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 90, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tip_general_risk_checklist', 'agent_general_assistant', '风险排查清单',
     '按“高/中/低风险”分组列出，并给每项一个可执行规避建议。',
     '帮我排查这个方案的风险。',
     NULL, NULL, CURRENT_TIMESTAMP, 'ACTIVE', 100, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS llm_provider_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider_id VARCHAR(64) NOT NULL DEFAULT '',
    provider_name VARCHAR(128) NOT NULL DEFAULT '',
    protocol VARCHAR(64) NOT NULL DEFAULT '',
    base_url VARCHAR(512) NOT NULL DEFAULT '',
    api_key_ciphertext TEXT NOT NULL,
    default_model VARCHAR(128) NOT NULL DEFAULT '',
    local TINYINT(1) NOT NULL DEFAULT 0,
    require_api_key TINYINT(1) NOT NULL DEFAULT 1,
    freeze_url TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    ext_config CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (provider_id),
    INDEX idx_llm_provider_config_status (status)
);

CREATE TABLE IF NOT EXISTS llm_provider_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider_id VARCHAR(64) NOT NULL DEFAULT '',
    model_id VARCHAR(128) NOT NULL DEFAULT '',
    model_name VARCHAR(255) NOT NULL DEFAULT '',
    capabilities_json CLOB NOT NULL,
    reasoning TINYINT(1) NOT NULL DEFAULT 0,
    context_window INT NOT NULL DEFAULT 0,
    max_input_tokens INT NOT NULL DEFAULT 0,
    max_output_tokens INT NOT NULL DEFAULT 0,
    upload_policy_json CLOB NULL,
    sort_index INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (provider_id, model_id),
    INDEX idx_llm_provider_model_provider (provider_id, status, sort_index)
);
