package ai.nomoclaw.bot.knowledge.ingestion;

import ai.nomoclaw.bot.knowledge.config.KnowledgeProperties;
import ai.nomoclaw.bot.knowledge.config.KnowledgePropertiesTestSupport;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class EmbeddingCacheStoreTest {
    private JdbcTemplate jdbc;
    private KnowledgeProperties properties;
    private EmbeddingCacheStore cache;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:embedding-cache;MODE=MySQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("DROP ALL OBJECTS");
        jdbc.execute("CREATE TABLE knowledge_embedding_cache (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "cache_key VARCHAR(64) UNIQUE,model_fingerprint VARCHAR(512),content_hash VARCHAR(64),dimension INT,"
                + "vector_blob BLOB,vector_bytes INT,hit_count BIGINT,created_time TIMESTAMP,last_access_time TIMESTAMP)");
        properties = KnowledgePropertiesTestSupport.properties();
        cache = new EmbeddingCacheStore(jdbc, properties);
    }

    @Test
    void persistsAndReadsFloatVectorsWithinFingerprintNamespace() {
        String key = cache.key("provider:model:3", "content");
        cache.put(key, "provider:model:3", "content", List.of(1F, 2F, 3F));

        assertThat(cache.get(key, 3)).contains(List.of(1F, 2F, 3F));
        assertThat(cache.get(cache.key("other:model:3", "content"), 3)).isEmpty();
        assertThat(jdbc.queryForObject("SELECT hit_count FROM knowledge_embedding_cache", Long.class)).isEqualTo(1L);
    }

    @Test
    void removesExpiredAndLeastRecentlyUsedEntries() {
        properties.getEmbeddingCache().setTtl(Duration.ofDays(1));
        properties.getEmbeddingCache().setMaxEntries(1);
        cache.put(cache.key("model", "old"), "model", "old", List.of(1F));
        jdbc.update("UPDATE knowledge_embedding_cache SET last_access_time=?",
                LocalDateTime.now().minusDays(2));
        cache.put(cache.key("model", "new"), "model", "new", List.of(2F));

        cache.cleanup();

        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM knowledge_embedding_cache", Integer.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT content_hash FROM knowledge_embedding_cache", String.class))
                .isEqualTo("new");
    }
}
