package ai.nomoclaw.bot.knowledge.app;

import ai.nomoclaw.bot.knowledge.TestRepositorySupport;
import ai.nomoclaw.bot.knowledge.config.KnowledgeProperties;
import ai.nomoclaw.bot.knowledge.config.KnowledgePropertiesTestSupport;
import ai.nomoclaw.bot.knowledge.core.mapper.KnowledgeDocumentMapper;
import ai.nomoclaw.bot.knowledge.core.mapper.KnowledgeIngestionJobMapper;
import ai.nomoclaw.bot.knowledge.core.repository.KnowledgeDocumentRepository;
import ai.nomoclaw.bot.knowledge.core.repository.KnowledgeIngestionJobRepository;
import ai.nomoclaw.bot.knowledge.core.repository.KnowledgePersistenceRepository;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler;

import java.sql.Timestamp;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Executor;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

class KnowledgeIngestionDispatcherTest {
    private KnowledgePersistenceRepository persistence;
    private KnowledgeProperties properties;
    private ListRecordingRunner runner;
    private ThreadPoolTaskScheduler scheduler;
    private KnowledgeIngestionDispatcher dispatcher;
    private KnowledgeIngestionJobRepository ingestionJobRepository;
    private KnowledgeDocumentRepository documentRepository;

    @BeforeEach
    void setUp() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:knowledge-dispatcher;MODE=MySQL;DB_CLOSE_DELAY=-1");
        persistence = new KnowledgePersistenceRepository(dataSource);
        persistence.execute("DROP ALL OBJECTS");
        persistence.execute("CREATE TABLE knowledge_ingestion_job (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "job_uid VARCHAR(64) NOT NULL UNIQUE, knowledge_base_uid VARCHAR(64), document_uid VARCHAR(64) NOT NULL, "
                + "document_version_uid VARCHAR(64), status VARCHAR(32) NOT NULL, stage VARCHAR(32) NOT NULL, "
                + "progress_percent INT NOT NULL DEFAULT 0, total_chunks INT NOT NULL DEFAULT 0, processed_chunks INT NOT NULL DEFAULT 0, "
                + "processed_pages INT NOT NULL DEFAULT 0, total_pages INT NOT NULL DEFAULT 0, cache_hit_chunks INT NOT NULL DEFAULT 0, "
                + "cache_miss_chunks INT NOT NULL DEFAULT 0, attempt_count INT NOT NULL DEFAULT 0, failure_code VARCHAR(64) NOT NULL DEFAULT '', "
                + "failure_message VARCHAR(1000), worker_id VARCHAR(128), lease_token VARCHAR(64), lease_until TIMESTAMP(3), "
                + "last_heartbeat_time TIMESTAMP(3), next_retry_time TIMESTAMP(3), retryable INT NOT NULL DEFAULT 0, "
                + "started_time TIMESTAMP(3), finished_time TIMESTAMP(3), created_time TIMESTAMP(3), updated_time TIMESTAMP(3) NOT NULL)");
        persistence.execute("CREATE TABLE knowledge_document (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "document_uid VARCHAR(64) UNIQUE,knowledge_base_uid VARCHAR(64),display_name VARCHAR(255),source_type VARCHAR(32),"
                + "original_file_name VARCHAR(255),content_type VARCHAR(128),file_path VARCHAR(1024),size_bytes BIGINT,"
                + "checksum_sha256 VARCHAR(64),current_version_uid VARCHAR(64),status VARCHAR(32) NOT NULL,"
                + "failure_code VARCHAR(64) NOT NULL DEFAULT '',failure_message VARCHAR(1000),page_count INT,chunk_count INT,"
                + "created_time TIMESTAMP(3),updated_time TIMESTAMP(3) NOT NULL)");
        TestRepositorySupport repositories = new TestRepositorySupport(dataSource);
        ingestionJobRepository = repositories.repository(KnowledgeIngestionJobRepository.class,
                KnowledgeIngestionJobMapper.class);
        documentRepository = repositories.repository(KnowledgeDocumentRepository.class, KnowledgeDocumentMapper.class);
        properties = KnowledgePropertiesTestSupport.properties();
        properties.getIngestion().setWorkerCount(2);
        properties.getIngestion().setLeaseSeconds(30);
        properties.getIngestion().setDispatchInterval(Duration.ofMillis(20));
        runner = new ListRecordingRunner();
        scheduler = new ThreadPoolTaskScheduler();
        scheduler.setPoolSize(2);
        scheduler.setThreadNamePrefix("knowledge-dispatcher-test-");
        scheduler.initialize();
        Executor directExecutor = Runnable::run;
        dispatcher = new KnowledgeIngestionDispatcher(ingestionJobRepository, documentRepository,
                properties, runner, directExecutor, scheduler);
    }

    @AfterEach
    void tearDown() {
        dispatcher.stop();
        scheduler.destroy();
    }

    @Test
    void claimsPendingAndExpiredRunningJobs() {
        insertJob("job_pending", "doc_pending", "PENDING", 0, null);
        insertJob("job_expired", "doc_expired", "RUNNING", 1, LocalDateTime.now().minusMinutes(1));

        dispatcher.start();

        waitForInvocationCount(runner, 2);
        assertEquals(2, persistence.queryForObject("SELECT COUNT(*) FROM knowledge_ingestion_job WHERE status='RUNNING' "
                + "AND worker_id IS NOT NULL AND lease_token IS NOT NULL", Integer.class));
    }

    @Test
    void exhaustedExpiredJobBecomesFailed() {
        properties.getIngestion().setMaxAttempts(3);
        insertDocument("doc_exhausted");
        insertJob("job_exhausted", "doc_exhausted", "RUNNING", 3, LocalDateTime.now().minusMinutes(1));

        dispatcher.start();

        waitUntilFailed("job_exhausted");
        assertEquals(0, runner.count());
        assertEquals("FAILED", persistence.queryForObject(
                "SELECT status FROM knowledge_document WHERE document_uid='doc_exhausted'", String.class));
        assertEquals("LEASE_EXPIRED", persistence.queryForObject(
                "SELECT failure_code FROM knowledge_ingestion_job WHERE job_uid='job_exhausted'", String.class));
    }

    @Test
    void activeLeaseIsNotClaimedTwice() {
        insertJob("job_active", "doc_active", "RUNNING", 1, LocalDateTime.now().plusMinutes(1));

        dispatcher.start();

        sleep(200);
        assertEquals(0, runner.count());
        assertEquals(1, persistence.queryForObject(
                "SELECT attempt_count FROM knowledge_ingestion_job WHERE job_uid='job_active'", Integer.class));
    }

    @Test
    void competingDispatchersClaimJobOnlyOnce() throws Exception {
        insertJob("job_competing", "doc_competing", "PENDING", 0, null);
        ListRecordingRunner otherRunner = new ListRecordingRunner();
        KnowledgeIngestionDispatcher other = new KnowledgeIngestionDispatcher(
                ingestionJobRepository, documentRepository, properties, otherRunner, Runnable::run, scheduler);
        try {
            dispatcher.start();
            other.start();
            Thread.sleep(250);
        } finally {
            other.stop();
        }

        int invocations = runner.count() + otherRunner.count();
        assertEquals(1, invocations);
        assertEquals(1, persistence.queryForObject(
                "SELECT attempt_count FROM knowledge_ingestion_job WHERE job_uid='job_competing'", Integer.class));
    }

    private void insertJob(String jobUid, String documentUid, String status, int attemptCount,
                           LocalDateTime leaseUntil) {
        persistence.update("INSERT INTO knowledge_ingestion_job(job_uid,document_uid,status,stage,attempt_count,lease_until,updated_time) "
                        + "VALUES(?,?,?,?,?,?,?)",
                jobUid, documentUid, status, "QUEUED", attemptCount,
                leaseUntil == null ? null : Timestamp.valueOf(leaseUntil), Timestamp.valueOf(LocalDateTime.now()));
    }

    private void insertDocument(String documentUid) {
        persistence.update("INSERT INTO knowledge_document(document_uid,status,failure_code,failure_message,updated_time) "
                        + "VALUES(?,?,?,?,?)",
                documentUid, "PROCESSING", "", "", Timestamp.valueOf(LocalDateTime.now()));
    }

    private void waitUntilFailed(String jobUid) {
        for (int attempt = 0; attempt < 50; attempt++) {
            String status = persistence.queryForObject(
                    "SELECT status FROM knowledge_ingestion_job WHERE job_uid=?", String.class, jobUid);
            if ("FAILED".equals(status)) return;
            try {
                Thread.sleep(20);
            } catch (InterruptedException ex) {
                Thread.currentThread().interrupt();
                throw new IllegalStateException(ex);
            }
        }
        fail("job did not reach FAILED: " + jobUid);
    }

    private void waitForInvocationCount(ListRecordingRunner target, int expected) {
        for (int attempt = 0; attempt < 75; attempt++) {
            if (target.count() >= expected) return;
            sleep(20);
        }
        fail("runner invocation count did not reach " + expected);
    }

    private void sleep(long millis) {
        try {
            Thread.sleep(millis);
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException(ex);
        }
    }

    private static final class ListRecordingRunner implements KnowledgeIngestionRunner {
        private final CopyOnWriteArrayList<String> jobUids = new CopyOnWriteArrayList<>();

        @Override
        public void runIngestion(String jobUid, String leaseToken) {
            jobUids.add(jobUid);
        }

        private int count() {
            return jobUids.size();
        }
    }
}
