package ai.nomoclaw.bot.knowledge.app;

import ai.nomoclaw.bot.knowledge.bm25.LexicalSearchStore;
import ai.nomoclaw.bot.knowledge.config.KnowledgeProperties;
import ai.nomoclaw.bot.knowledge.ingestion.DocumentChunker;
import ai.nomoclaw.bot.knowledge.ingestion.DocumentParser;
import ai.nomoclaw.bot.knowledge.ingestion.EmbeddingProvider;
import ai.nomoclaw.bot.knowledge.model.KnowledgeModels;
import ai.nomoclaw.bot.knowledge.rerank.NoopReranker;
import ai.nomoclaw.bot.knowledge.vector.VectorStore;
import io.micrometer.core.instrument.MeterRegistry;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.beans.factory.support.DefaultListableBeanFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.transaction.support.TransactionTemplate;

import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class KnowledgeUploadServiceTest {
    @TempDir
    Path storageRoot;

    private JdbcTemplate jdbc;
    private KnowledgeService service;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:knowledge-upload;MODE=MySQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("DROP ALL OBJECTS");
        createSchema();
        KnowledgeProperties properties = new KnowledgeProperties();
        properties.setStorageRoot(storageRoot);
        TransactionTemplate transactions = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        DefaultListableBeanFactory beanFactory = new DefaultListableBeanFactory();
        KnowledgeIngestionMetrics metrics = new KnowledgeIngestionMetrics(
                beanFactory.getBeanProvider(MeterRegistry.class));
        service = new KnowledgeService(jdbc, transactions, properties, new TextParser(), new EmptyChunker(),
                new EmptyEmbeddingProvider(), new EmptyVectorStore(), Runnable::run, null, null,
                new EmptyLexicalStore(), new NoopReranker(), metrics);
        LocalDateTime now = LocalDateTime.now();
        jdbc.update("INSERT INTO knowledge_base(knowledge_base_uid,name,description,status,embedding_provider_id,"
                        + "embedding_model_id,embedding_dimension,vector_collection_name,chunk_size_tokens,chunk_overlap_tokens,"
                        + "retrieval_top_k,similarity_threshold,document_count,chunk_count,created_time,updated_time) "
                        + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                "kb_test", "Test", "", "ACTIVE", "provider", "model", 3, "collection", 500, 80,
                8, .35, 0, 0, now, now);
    }

    @Test
    void reportsAcceptedDuplicateAndRejectedFilesIndependently() {
        MockMultipartFile accepted = new MockMultipartFile("files", "a.txt", "text/plain", "same content".getBytes());
        MockMultipartFile duplicate = new MockMultipartFile("files", "b.txt", "text/plain", "same content".getBytes());
        MockMultipartFile rejected = new MockMultipartFile("files", "c.exe", "application/octet-stream", new byte[]{1});

        KnowledgeModels.UploadResult result = service.upload("kb_test", List.of(accepted, duplicate, rejected));

        assertEquals(List.of("ACCEPTED", "DUPLICATE", "REJECTED"),
                result.items().stream().map(KnowledgeModels.UploadFileResult::outcome).toList());
        assertEquals(2, result.documents().size());
        assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM knowledge_document", Integer.class));
        assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM knowledge_ingestion_job", Integer.class));
    }

    private void createSchema() {
        jdbc.execute("CREATE TABLE knowledge_base (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_base_uid VARCHAR(64) UNIQUE, "
                + "name VARCHAR(255), description VARCHAR(1000), status VARCHAR(32), embedding_provider_id VARCHAR(64), embedding_model_id VARCHAR(128), "
                + "embedding_dimension INT, vector_collection_name VARCHAR(128), chunk_size_tokens INT, chunk_overlap_tokens INT, retrieval_top_k INT, "
                + "similarity_threshold DOUBLE, document_count INT, chunk_count BIGINT, created_time TIMESTAMP, updated_time TIMESTAMP)");
        jdbc.execute("CREATE TABLE knowledge_document (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_uid VARCHAR(64) UNIQUE, "
                + "knowledge_base_uid VARCHAR(64), display_name VARCHAR(255), source_type VARCHAR(32), original_file_name VARCHAR(255), content_type VARCHAR(128), "
                + "file_path VARCHAR(1024), size_bytes BIGINT, checksum_sha256 VARCHAR(64), current_version_uid VARCHAR(64), status VARCHAR(32), "
                + "failure_code VARCHAR(64), failure_message VARCHAR(1000), page_count INT, chunk_count INT, created_time TIMESTAMP, updated_time TIMESTAMP, "
                + "CONSTRAINT uk_doc_checksum UNIQUE(knowledge_base_uid, checksum_sha256))");
        jdbc.execute("CREATE TABLE knowledge_document_version (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_version_uid VARCHAR(64) UNIQUE, "
                + "document_uid VARCHAR(64), version_no INT, checksum_sha256 VARCHAR(64), parser_version VARCHAR(32), chunker_version VARCHAR(32), "
                + "embedding_model_fingerprint VARCHAR(255), status VARCHAR(32), created_time TIMESTAMP)");
        jdbc.execute("CREATE TABLE knowledge_ingestion_job (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_uid VARCHAR(64) UNIQUE, "
                + "knowledge_base_uid VARCHAR(64), document_uid VARCHAR(64), document_version_uid VARCHAR(64), status VARCHAR(32), stage VARCHAR(32), "
                + "progress_percent INT, total_chunks INT, processed_chunks INT, attempt_count INT, failure_code VARCHAR(64), failure_message VARCHAR(1000), "
                + "worker_id VARCHAR(128), lease_token VARCHAR(64), lease_until TIMESTAMP, last_heartbeat_time TIMESTAMP, next_retry_time TIMESTAMP, "
                + "retryable INT, started_time TIMESTAMP, finished_time TIMESTAMP, created_time TIMESTAMP, updated_time TIMESTAMP)");
    }

    private static final class TextParser implements DocumentParser {
        @Override
        public boolean supports(String contentType, String fileName) {
            return fileName.endsWith(".txt");
        }

        @Override
        public ParsedDocument parse(Path file) {
            return new ParsedDocument(List.of());
        }
    }

    private static final class EmptyChunker implements DocumentChunker {
        @Override
        public List<Chunk> split(DocumentParser.ParsedDocument document, int sizeTokens, int overlapTokens) {
            return List.of();
        }
    }

    private static final class EmptyEmbeddingProvider implements EmbeddingProvider {
        @Override
        public List<List<Float>> embed(List<String> texts, String providerId, String modelId, int expectedDimension) {
            return List.of();
        }
    }

    private static final class EmptyVectorStore implements VectorStore {
        @Override public void ensureCollection(String collection, int dimension) { }
        @Override public void upsert(String collection, List<Point> points) { }
        @Override public List<Hit> search(String collection, List<Float> vector, List<String> knowledgeBaseUids, int limit) { return List.of(); }
        @Override public void deleteByDocument(String collection, String documentUid) { }
        @Override public void deleteByDocumentVersion(String collection, String documentVersionUid) { }
        @Override public boolean available() { return true; }
    }

    private static final class EmptyLexicalStore implements LexicalSearchStore {
        @Override public void replaceDocument(String knowledgeBaseUid, String documentUid, String documentVersionUid, String documentName, List<IndexedChunk> chunks) { }
        @Override public List<Hit> search(String query, List<String> knowledgeBaseUids, int limit) { return List.of(); }
        @Override public void deleteByDocument(String documentUid) { }
        @Override public void deleteByKnowledgeBase(String knowledgeBaseUid) { }
        @Override public void clear() { }
        @Override public boolean available() { return false; }
    }
}
