package ai.nomoclaw.bot.knowledge.app;

import ai.nomoclaw.bot.knowledge.config.KnowledgeProperties;
import ai.nomoclaw.bot.knowledge.config.KnowledgePropertiesTestSupport;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler;

import java.sql.Timestamp;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Executor;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

class KnowledgeIngestionDispatcherTest {
    private JdbcTemplate jdbc;
    private KnowledgeProperties properties;
    private ListRecordingRunner runner;
    private ThreadPoolTaskScheduler scheduler;
    private KnowledgeIngestionDispatcher dispatcher;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:knowledge-dispatcher;MODE=MySQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("DROP ALL OBJECTS");
        jdbc.execute("CREATE TABLE knowledge_ingestion_job (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "job_uid VARCHAR(64) NOT NULL UNIQUE, document_uid VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, "
                + "stage VARCHAR(32) NOT NULL, progress_percent INT NOT NULL DEFAULT 0, total_chunks INT NOT NULL DEFAULT 0, "
                + "processed_chunks INT NOT NULL DEFAULT 0, attempt_count INT NOT NULL DEFAULT 0, failure_code VARCHAR(64) NOT NULL DEFAULT '', "
                + "failure_message VARCHAR(1000), worker_id VARCHAR(128), lease_token VARCHAR(64), lease_until TIMESTAMP(3), "
                + "last_heartbeat_time TIMESTAMP(3), next_retry_time TIMESTAMP(3), retryable INT NOT NULL DEFAULT 0, "
                + "started_time TIMESTAMP(3), finished_time TIMESTAMP(3), updated_time TIMESTAMP(3) NOT NULL)");
        jdbc.execute("CREATE TABLE knowledge_document (document_uid VARCHAR(64) PRIMARY KEY, status VARCHAR(32) NOT NULL, "
                + "failure_code VARCHAR(64) NOT NULL DEFAULT '', failure_message VARCHAR(1000), updated_time TIMESTAMP(3) NOT NULL)");
        properties = KnowledgePropertiesTestSupport.properties();
        properties.getIngestion().setWorkerCount(2);
        properties.getIngestion().setLeaseSeconds(30);
        properties.getIngestion().setDispatchInterval(Duration.ofMillis(20));
        runner = new ListRecordingRunner();
        scheduler = new ThreadPoolTaskScheduler();
        scheduler.setPoolSize(2);
        scheduler.setThreadNamePrefix("knowledge-dispatcher-test-");
        scheduler.initialize();
        Executor directExecutor = Runnable::run;
        dispatcher = new KnowledgeIngestionDispatcher(jdbc, properties, runner, directExecutor, scheduler);
    }

    @AfterEach
    void tearDown() {
        dispatcher.stop();
        scheduler.destroy();
    }

    @Test
    void claimsPendingAndExpiredRunningJobs() {
        insertJob("job_pending", "doc_pending", "PENDING", 0, null);
        insertJob("job_expired", "doc_expired", "RUNNING", 1, LocalDateTime.now().minusMinutes(1));

        dispatcher.start();

        waitForInvocationCount(runner, 2);
        assertEquals(2, jdbc.queryForObject("SELECT COUNT(*) FROM knowledge_ingestion_job WHERE status='RUNNING' "
                + "AND worker_id IS NOT NULL AND lease_token IS NOT NULL", Integer.class));
    }

    @Test
    void exhaustedExpiredJobBecomesFailed() {
        properties.getIngestion().setMaxAttempts(3);
        insertDocument("doc_exhausted");
        insertJob("job_exhausted", "doc_exhausted", "RUNNING", 3, LocalDateTime.now().minusMinutes(1));

        dispatcher.start();

        waitUntilFailed("job_exhausted");
        assertEquals(0, runner.count());
        assertEquals("FAILED", jdbc.queryForObject(
                "SELECT status FROM knowledge_document WHERE document_uid='doc_exhausted'", String.class));
        assertEquals("LEASE_EXPIRED", jdbc.queryForObject(
                "SELECT failure_code FROM knowledge_ingestion_job WHERE job_uid='job_exhausted'", String.class));
    }

    @Test
    void activeLeaseIsNotClaimedTwice() {
        insertJob("job_active", "doc_active", "RUNNING", 1, LocalDateTime.now().plusMinutes(1));

        dispatcher.start();

        sleep(200);
        assertEquals(0, runner.count());
        assertEquals(1, jdbc.queryForObject(
                "SELECT attempt_count FROM knowledge_ingestion_job WHERE job_uid='job_active'", Integer.class));
    }

    @Test
    void competingDispatchersClaimJobOnlyOnce() throws Exception {
        insertJob("job_competing", "doc_competing", "PENDING", 0, null);
        ListRecordingRunner otherRunner = new ListRecordingRunner();
        KnowledgeIngestionDispatcher other = new KnowledgeIngestionDispatcher(
                jdbc, properties, otherRunner, Runnable::run, scheduler);
        try {
            dispatcher.start();
            other.start();
            Thread.sleep(250);
        } finally {
            other.stop();
        }

        int invocations = runner.count() + otherRunner.count();
        assertEquals(1, invocations);
        assertEquals(1, jdbc.queryForObject(
                "SELECT attempt_count FROM knowledge_ingestion_job WHERE job_uid='job_competing'", Integer.class));
    }

    private void insertJob(String jobUid, String documentUid, String status, int attemptCount,
                           LocalDateTime leaseUntil) {
        jdbc.update("INSERT INTO knowledge_ingestion_job(job_uid,document_uid,status,stage,attempt_count,lease_until,updated_time) "
                        + "VALUES(?,?,?,?,?,?,?)",
                jobUid, documentUid, status, "QUEUED", attemptCount,
                leaseUntil == null ? null : Timestamp.valueOf(leaseUntil), Timestamp.valueOf(LocalDateTime.now()));
    }

    private void insertDocument(String documentUid) {
        jdbc.update("INSERT INTO knowledge_document(document_uid,status,failure_code,failure_message,updated_time) "
                        + "VALUES(?,?,?,?,?)",
                documentUid, "PROCESSING", "", "", Timestamp.valueOf(LocalDateTime.now()));
    }

    private void waitUntilFailed(String jobUid) {
        for (int attempt = 0; attempt < 50; attempt++) {
            String status = jdbc.queryForObject(
                    "SELECT status FROM knowledge_ingestion_job WHERE job_uid=?", String.class, jobUid);
            if ("FAILED".equals(status)) return;
            try {
                Thread.sleep(20);
            } catch (InterruptedException ex) {
                Thread.currentThread().interrupt();
                throw new IllegalStateException(ex);
            }
        }
        fail("job did not reach FAILED: " + jobUid);
    }

    private void waitForInvocationCount(ListRecordingRunner target, int expected) {
        for (int attempt = 0; attempt < 75; attempt++) {
            if (target.count() >= expected) return;
            sleep(20);
        }
        fail("runner invocation count did not reach " + expected);
    }

    private void sleep(long millis) {
        try {
            Thread.sleep(millis);
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException(ex);
        }
    }

    private static final class ListRecordingRunner implements KnowledgeIngestionRunner {
        private final CopyOnWriteArrayList<String> jobUids = new CopyOnWriteArrayList<>();

        @Override
        public void runIngestion(String jobUid, String leaseToken) {
            jobUids.add(jobUid);
        }

        private int count() {
            return jobUids.size();
        }
    }
}
