CREATE TABLE IF NOT EXISTS knowledge_import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_uid VARCHAR(64) NOT NULL UNIQUE,
    knowledge_base_uid VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    parser_mode VARCHAR(32) DEFAULT 'STRUCTURED' NOT NULL,
    chunk_size_tokens INT DEFAULT 500 NOT NULL,
    chunk_overlap_tokens INT DEFAULT 80 NOT NULL,
    embedding_provider_id VARCHAR(64) DEFAULT '' NOT NULL,
    embedding_model_id VARCHAR(128) DEFAULT '' NOT NULL,
    embedding_dimension INT DEFAULT 0 NOT NULL,
    embedding_model_fingerprint VARCHAR(512) DEFAULT '' NOT NULL,
    config_hash VARCHAR(64) DEFAULT '' NOT NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_knowledge_import_batch_base
    ON knowledge_import_batch(knowledge_base_uid, status, id);

CREATE TABLE IF NOT EXISTS knowledge_import_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_uid VARCHAR(64) NOT NULL UNIQUE,
    batch_uid VARCHAR(64) NOT NULL,
    document_uid VARCHAR(64),
    document_version_uid VARCHAR(64),
    original_file_name VARCHAR(255) NOT NULL,
    mode VARCHAR(16) DEFAULT 'UPLOAD' NOT NULL,
    outcome VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    error_code VARCHAR(64) DEFAULT '' NOT NULL,
    error_message CLOB,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_knowledge_import_item_batch ON knowledge_import_item(batch_uid, id);
CREATE INDEX IF NOT EXISTS idx_knowledge_import_item_version ON knowledge_import_item(document_version_uid);

ALTER TABLE knowledge_document_version ADD COLUMN IF NOT EXISTS parser_mode VARCHAR(32) DEFAULT 'STRUCTURED' NOT NULL;
ALTER TABLE knowledge_document_version ADD COLUMN IF NOT EXISTS chunk_size_tokens INT DEFAULT 500 NOT NULL;
ALTER TABLE knowledge_document_version ADD COLUMN IF NOT EXISTS chunk_overlap_tokens INT DEFAULT 80 NOT NULL;
ALTER TABLE knowledge_document_version ADD COLUMN IF NOT EXISTS build_mode VARCHAR(16) DEFAULT 'INITIAL' NOT NULL;
ALTER TABLE knowledge_document_version ADD COLUMN IF NOT EXISTS embedding_provider_id VARCHAR(64) DEFAULT '' NOT NULL;
ALTER TABLE knowledge_document_version ADD COLUMN IF NOT EXISTS embedding_model_id VARCHAR(128) DEFAULT '' NOT NULL;
ALTER TABLE knowledge_document_version ADD COLUMN IF NOT EXISTS embedding_dimension INT DEFAULT 0 NOT NULL;
ALTER TABLE knowledge_document_version ADD COLUMN IF NOT EXISTS parse_warnings CLOB;

ALTER TABLE knowledge_ingestion_job ADD COLUMN IF NOT EXISTS processed_pages INT DEFAULT 0 NOT NULL;
ALTER TABLE knowledge_ingestion_job ADD COLUMN IF NOT EXISTS total_pages INT DEFAULT 0 NOT NULL;
ALTER TABLE knowledge_ingestion_job ADD COLUMN IF NOT EXISTS cache_hit_chunks INT DEFAULT 0 NOT NULL;
ALTER TABLE knowledge_ingestion_job ADD COLUMN IF NOT EXISTS cache_miss_chunks INT DEFAULT 0 NOT NULL;

UPDATE knowledge_document_version v
SET parser_mode = 'STRUCTURED',
    chunk_size_tokens = (SELECT b.chunk_size_tokens
                         FROM knowledge_document d
                         JOIN knowledge_base b ON b.knowledge_base_uid = d.knowledge_base_uid
                         WHERE d.document_uid = v.document_uid),
    chunk_overlap_tokens = (SELECT b.chunk_overlap_tokens
                            FROM knowledge_document d
                            JOIN knowledge_base b ON b.knowledge_base_uid = d.knowledge_base_uid
                            WHERE d.document_uid = v.document_uid),
    embedding_provider_id = (SELECT b.embedding_provider_id
                             FROM knowledge_document d
                             JOIN knowledge_base b ON b.knowledge_base_uid = d.knowledge_base_uid
                             WHERE d.document_uid = v.document_uid),
    embedding_model_id = (SELECT b.embedding_model_id
                          FROM knowledge_document d
                          JOIN knowledge_base b ON b.knowledge_base_uid = d.knowledge_base_uid
                          WHERE d.document_uid = v.document_uid),
    embedding_dimension = (SELECT b.embedding_dimension
                           FROM knowledge_document d
                           JOIN knowledge_base b ON b.knowledge_base_uid = d.knowledge_base_uid
                           WHERE d.document_uid = v.document_uid)
WHERE v.embedding_provider_id = '' OR v.embedding_dimension = 0;

CREATE TABLE IF NOT EXISTS knowledge_embedding_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key VARCHAR(64) NOT NULL UNIQUE,
    model_fingerprint VARCHAR(512) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    dimension INT NOT NULL,
    vector_blob BLOB NOT NULL,
    vector_bytes INT NOT NULL,
    hit_count BIGINT DEFAULT 0 NOT NULL,
    created_time TIMESTAMP(3) NOT NULL,
    last_access_time TIMESTAMP(3) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_knowledge_embedding_cache_cleanup
    ON knowledge_embedding_cache(last_access_time, id);
CREATE INDEX IF NOT EXISTS idx_knowledge_embedding_cache_content
    ON knowledge_embedding_cache(content_hash);
