package ai.nomoclaw.bot.policy.tool;

public enum ToolPolicyReasonCode {
    NONE,
    HARD_GUARD_SENSITIVE_PATH_READ_DENY,
    HARD_GUARD_SENSITIVE_PATH_READ_ASK,
    HARD_GUARD_PROTECTED_PATH_ASK,
    HARD_GUARD_SYSTEM_PATH_DENY,
    RULE_DENY_MATCHED,
    RULE_ASK_MATCHED,
    RULE_ALLOW_MATCHED,
    DEFAULT_REQUIRE_APPROVAL,
    INVALID_RULE_IGNORED,
    POLICY_BLOCKED_SYSTEM_PATH_WRITE,
    POLICY_BLOCKED_BY_DENY_RULE,
    POLICY_WRITE_OUTSIDE_ALLOWED_SCOPE,
    POLICY_REQUIRE_APPROVAL_HIGH_RISK
}
