CREATE TABLE IF NOT EXISTS knowledge_base (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_base_uid VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(255) NOT NULL,
 description CLOB, status VARCHAR(32) NOT NULL, embedding_provider_id VARCHAR(64) NOT NULL, embedding_model_id VARCHAR(128) NOT NULL,
 embedding_dimension INT NOT NULL, chunk_size_tokens INT NOT NULL, chunk_overlap_tokens INT NOT NULL, retrieval_top_k INT NOT NULL,
 similarity_threshold DOUBLE PRECISION NOT NULL, document_count INT DEFAULT 0 NOT NULL, chunk_count BIGINT DEFAULT 0 NOT NULL,
 created_time TIMESTAMP(3) NOT NULL, updated_time TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS knowledge_document (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_uid VARCHAR(64) NOT NULL UNIQUE, knowledge_base_uid VARCHAR(64) NOT NULL,
 display_name VARCHAR(255) NOT NULL, source_type VARCHAR(32) NOT NULL, original_file_name VARCHAR(255) NOT NULL, content_type VARCHAR(128) NOT NULL,
 file_path VARCHAR(1024) NOT NULL, size_bytes BIGINT NOT NULL, checksum_sha256 VARCHAR(64) NOT NULL, current_version_uid VARCHAR(64) DEFAULT '' NOT NULL,
 status VARCHAR(32) NOT NULL, failure_code VARCHAR(64) DEFAULT '' NOT NULL, failure_message CLOB, page_count INT DEFAULT 0 NOT NULL,
 chunk_count INT DEFAULT 0 NOT NULL, created_time TIMESTAMP(3) NOT NULL, updated_time TIMESTAMP(3) NOT NULL,
 CONSTRAINT uk_knowledge_document_checksum UNIQUE (knowledge_base_uid, checksum_sha256));
CREATE INDEX IF NOT EXISTS idx_knowledge_document_base ON knowledge_document(knowledge_base_uid, status, id);
CREATE TABLE IF NOT EXISTS knowledge_document_version (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_version_uid VARCHAR(64) NOT NULL UNIQUE, document_uid VARCHAR(64) NOT NULL,
 version_no INT NOT NULL, checksum_sha256 VARCHAR(64) NOT NULL, parser_version VARCHAR(32) NOT NULL, chunker_version VARCHAR(32) NOT NULL,
 embedding_model_fingerprint VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL, created_time TIMESTAMP(3) NOT NULL,
 CONSTRAINT uk_knowledge_document_version UNIQUE(document_uid, version_no));
CREATE TABLE IF NOT EXISTS knowledge_chunk (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chunk_uid VARCHAR(64) NOT NULL UNIQUE, knowledge_base_uid VARCHAR(64) NOT NULL,
 document_uid VARCHAR(64) NOT NULL, document_version_uid VARCHAR(64) NOT NULL, chunk_index INT NOT NULL, content CLOB NOT NULL,
 token_count INT NOT NULL, content_hash VARCHAR(64) NOT NULL, page_from INT, page_to INT, section_path VARCHAR(1024) DEFAULT '' NOT NULL,
 char_start INT DEFAULT 0 NOT NULL, char_end INT DEFAULT 0 NOT NULL, vector_point_id VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL,
 created_time TIMESTAMP(3) NOT NULL);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_base_document ON knowledge_chunk(knowledge_base_uid, document_uid);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_version ON knowledge_chunk(document_version_uid);
CREATE TABLE IF NOT EXISTS knowledge_ingestion_job (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_uid VARCHAR(64) NOT NULL UNIQUE, knowledge_base_uid VARCHAR(64) NOT NULL,
 document_uid VARCHAR(64) NOT NULL, document_version_uid VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, progress_percent INT DEFAULT 0 NOT NULL,
 total_chunks INT DEFAULT 0 NOT NULL, processed_chunks INT DEFAULT 0 NOT NULL, attempt_count INT DEFAULT 0 NOT NULL,
 failure_code VARCHAR(64) DEFAULT '' NOT NULL, failure_message CLOB, lease_until TIMESTAMP(3), started_time TIMESTAMP(3), finished_time TIMESTAMP(3),
 created_time TIMESTAMP(3) NOT NULL, updated_time TIMESTAMP(3) NOT NULL);
CREATE INDEX IF NOT EXISTS idx_knowledge_job_status ON knowledge_ingestion_job(status, lease_until, id);
CREATE TABLE IF NOT EXISTS agent_knowledge_base_relation (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, agent_uid VARCHAR(64) NOT NULL, knowledge_base_uid VARCHAR(64) NOT NULL, enabled INT DEFAULT 1 NOT NULL, created_time TIMESTAMP(3) NOT NULL, updated_time TIMESTAMP(3) NOT NULL, CONSTRAINT uk_agent_knowledge_base UNIQUE(agent_uid, knowledge_base_uid));
CREATE TABLE IF NOT EXISTS conversation_knowledge_base_relation (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversation_uid VARCHAR(64) NOT NULL, knowledge_base_uid VARCHAR(64) NOT NULL, mode VARCHAR(16) NOT NULL, created_time TIMESTAMP(3) NOT NULL, updated_time TIMESTAMP(3) NOT NULL, CONSTRAINT uk_conversation_knowledge_base UNIQUE(conversation_uid, knowledge_base_uid));
CREATE TABLE IF NOT EXISTS knowledge_retrieval_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, retrieval_uid VARCHAR(64) NOT NULL UNIQUE, conversation_uid VARCHAR(64) NOT NULL, message_uid VARCHAR(64) NOT NULL, query_text CLOB NOT NULL, knowledge_base_uids CLOB NOT NULL, embedding_model_fingerprint VARCHAR(255) NOT NULL, candidate_count INT NOT NULL, selected_count INT NOT NULL, latency_ms BIGINT NOT NULL, status VARCHAR(32) NOT NULL, error_message CLOB, created_time TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS message_knowledge_citation (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, message_uid VARCHAR(64) NOT NULL, assistant_message_uid VARCHAR(64) DEFAULT '' NOT NULL, retrieval_uid VARCHAR(64) NOT NULL, chunk_uid VARCHAR(64) NOT NULL, rank_index INT NOT NULL, score DOUBLE PRECISION NOT NULL, created_time TIMESTAMP(3) NOT NULL, CONSTRAINT uk_message_knowledge_citation UNIQUE(message_uid, retrieval_uid, chunk_uid));
