CREATE TABLE IF NOT EXISTS mcp_server_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    server_uid VARCHAR(64) NOT NULL DEFAULT '',
    server_name VARCHAR(64) NOT NULL DEFAULT '',
    display_name VARCHAR(128) NOT NULL DEFAULT '',
    transport VARCHAR(16) NOT NULL DEFAULT 'HTTP',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    timeout_seconds INT NOT NULL DEFAULT 30,
    auto_start TINYINT(1) NOT NULL DEFAULT 1,
    config_json CLOB NULL,
    last_connected_time TIMESTAMP(3) NULL,
    last_error CLOB NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (server_uid),
    UNIQUE (server_name),
    INDEX idx_mcp_server_status (status)
);

CREATE TABLE IF NOT EXISTS mcp_tool_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    snapshot_uid VARCHAR(64) NOT NULL DEFAULT '',
    server_uid VARCHAR(64) NOT NULL DEFAULT '',
    tool_key VARCHAR(64) NOT NULL DEFAULT '',
    original_tool_name VARCHAR(128) NOT NULL DEFAULT '',
    display_name VARCHAR(128) NOT NULL DEFAULT '',
    description CLOB NULL,
    input_schema_json CLOB NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    last_synced_time TIMESTAMP(3) NOT NULL,
    created_time TIMESTAMP(3) NOT NULL,
    updated_time TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (snapshot_uid),
    UNIQUE (tool_key),
    UNIQUE (server_uid, original_tool_name),
    INDEX idx_mcp_tool_server (server_uid, status)
);
