CREATE TABLE IF NOT EXISTS llm_trace (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    trace_uid VARCHAR(64) NOT NULL,
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    request_uid VARCHAR(64) NOT NULL DEFAULT '',
    scene VARCHAR(64) NOT NULL DEFAULT '',
    round_index INT NOT NULL DEFAULT 1,
    attempt_index INT NOT NULL DEFAULT 1,
    provider VARCHAR(64) NOT NULL DEFAULT '',
    model_name VARCHAR(128) NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'REQUESTED',
    request_started_time DATETIME(3) NOT NULL,
    response_finished_time DATETIME(3) NULL,
    latency_ms BIGINT NULL,
    system_prompt LONGTEXT NOT NULL,
    request_messages LONGTEXT NOT NULL,
    tool_specifications LONGTEXT NOT NULL,
    tool_choice LONGTEXT NOT NULL,
    request_metadata LONGTEXT NOT NULL,
    response_content LONGTEXT NULL,
    response_tool_calls LONGTEXT NULL,
    finish_reason VARCHAR(64) NOT NULL DEFAULT '',
    input_tokens INT NOT NULL DEFAULT 0,
    cached_input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    usage_available TINYINT(1) NOT NULL DEFAULT 0,
    error_type VARCHAR(255) NOT NULL DEFAULT '',
    error_message LONGTEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_llm_trace_uid (trace_uid),
    UNIQUE KEY uk_llm_trace_request_uid (request_uid),
    KEY idx_llm_trace_conversation_message_time (conversation_uid, message_uid, request_started_time),
    KEY idx_llm_trace_message_round_attempt (message_uid, round_index, attempt_index)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='LLM 请求响应 Trace';

ALTER TABLE token_usage_record ADD COLUMN trace_uid VARCHAR(64) NOT NULL DEFAULT '' AFTER message_uid;
CREATE INDEX idx_token_usage_record_trace ON token_usage_record(trace_uid);
