ALTER TABLE knowledge_import_batch ADD COLUMN IF NOT EXISTS chunk_strategy VARCHAR(32) DEFAULT 'TOKEN' NOT NULL;
ALTER TABLE knowledge_document_version ADD COLUMN IF NOT EXISTS chunk_strategy VARCHAR(32) DEFAULT 'TOKEN' NOT NULL;
ALTER TABLE knowledge_chunk ADD COLUMN IF NOT EXISTS document_node_uid VARCHAR(64);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_node ON knowledge_chunk(document_node_uid);

CREATE TABLE IF NOT EXISTS knowledge_document_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_uid VARCHAR(64) NOT NULL UNIQUE,
    knowledge_base_uid VARCHAR(64) NOT NULL,
    document_uid VARCHAR(64) NOT NULL,
    document_version_uid VARCHAR(64) NOT NULL,
    parent_node_uid VARCHAR(64),
    node_type VARCHAR(32) NOT NULL,
    level INT DEFAULT 0 NOT NULL,
    code VARCHAR(128) DEFAULT '' NOT NULL,
    title VARCHAR(1024) DEFAULT '' NOT NULL,
    section_path VARCHAR(2048) DEFAULT '' NOT NULL,
    page_from INT,
    page_to INT,
    char_start INT DEFAULT 0 NOT NULL,
    char_end INT DEFAULT 0 NOT NULL,
    detection_source VARCHAR(32) DEFAULT 'FALLBACK' NOT NULL,
    confidence DECIMAL(5,4) DEFAULT 0 NOT NULL,
    indexable BOOLEAN DEFAULT TRUE NOT NULL,
    metadata_json CLOB,
    created_time TIMESTAMP(3) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_knowledge_node_document_version
    ON knowledge_document_node(document_version_uid, id);
CREATE INDEX IF NOT EXISTS idx_knowledge_node_parent ON knowledge_document_node(parent_node_uid);
