CREATE TABLE IF NOT EXISTS llm_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_uid VARCHAR(64) NOT NULL UNIQUE,
    conversation_uid VARCHAR(64) NOT NULL DEFAULT '',
    message_uid VARCHAR(64) NOT NULL DEFAULT '',
    request_uid VARCHAR(64) NOT NULL DEFAULT '' UNIQUE,
    scene VARCHAR(64) NOT NULL DEFAULT '',
    round_index INT NOT NULL DEFAULT 1,
    attempt_index INT NOT NULL DEFAULT 1,
    provider VARCHAR(64) NOT NULL DEFAULT '',
    model_name VARCHAR(128) NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'REQUESTED',
    request_started_time TIMESTAMP NOT NULL,
    response_finished_time TIMESTAMP NULL,
    latency_ms BIGINT NULL,
    system_prompt CLOB NOT NULL,
    request_messages CLOB NOT NULL,
    tool_specifications CLOB NOT NULL,
    tool_choice CLOB NOT NULL,
    request_metadata CLOB NOT NULL,
    response_content CLOB NULL,
    response_tool_calls CLOB NULL,
    finish_reason VARCHAR(64) NOT NULL DEFAULT '',
    input_tokens INT NOT NULL DEFAULT 0,
    cached_input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    usage_available BOOLEAN NOT NULL DEFAULT FALSE,
    error_type VARCHAR(255) NOT NULL DEFAULT '',
    error_message CLOB NULL
);
CREATE INDEX IF NOT EXISTS idx_llm_trace_conversation_message_time ON llm_trace(conversation_uid, message_uid, request_started_time);
CREATE INDEX IF NOT EXISTS idx_llm_trace_message_round_attempt ON llm_trace(message_uid, round_index, attempt_index);
ALTER TABLE token_usage_record ADD trace_uid VARCHAR(64) NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_token_usage_record_trace ON token_usage_record(trace_uid);
