package ai.nomoclaw.bot.knowledge;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/** Database helpers for tests that need the real knowledge schema. */
public final class TestDatabaseSupport {

    private TestDatabaseSupport() {
    }

    /** Applies the knowledge H2 schema from the shared db-schema module. */
    public static void migrateKnowledgeSchema(DataSource dataSource) {
        Flyway.configure()
                .dataSource(dataSource)
                .locations("classpath:db/migration/h2")
                .target(MigrationVersion.fromVersion("8"))
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .load()
                .migrate();
        applyStructuredChunkingSchema(dataSource);
    }

    private static void applyStructuredChunkingSchema(DataSource dataSource) {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("ALTER TABLE knowledge_import_batch ADD COLUMN IF NOT EXISTS chunk_strategy VARCHAR(32) DEFAULT 'TOKEN' NOT NULL");
            statement.execute("ALTER TABLE knowledge_document_version ADD COLUMN IF NOT EXISTS chunk_strategy VARCHAR(32) DEFAULT 'TOKEN' NOT NULL");
            statement.execute("ALTER TABLE knowledge_chunk ADD COLUMN IF NOT EXISTS document_node_uid VARCHAR(64)");
            statement.execute("CREATE TABLE IF NOT EXISTS knowledge_document_node ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, node_uid VARCHAR(64) NOT NULL UNIQUE, "
                    + "knowledge_base_uid VARCHAR(64) NOT NULL, document_uid VARCHAR(64) NOT NULL, "
                    + "document_version_uid VARCHAR(64) NOT NULL, parent_node_uid VARCHAR(64), node_type VARCHAR(32) NOT NULL, "
                    + "level INT DEFAULT 0 NOT NULL, code VARCHAR(128) DEFAULT '' NOT NULL, title VARCHAR(1024) DEFAULT '' NOT NULL, "
                    + "section_path VARCHAR(2048) DEFAULT '' NOT NULL, page_from INT, page_to INT, char_start INT DEFAULT 0 NOT NULL, "
                    + "char_end INT DEFAULT 0 NOT NULL, detection_source VARCHAR(32) DEFAULT 'FALLBACK' NOT NULL, "
                    + "confidence DECIMAL(5,4) DEFAULT 0 NOT NULL, indexable BOOLEAN DEFAULT TRUE NOT NULL, "
                    + "node_role VARCHAR(32) DEFAULT 'ROOT' NOT NULL, source_order INT DEFAULT 0 NOT NULL, "
                    + "quality_score DECIMAL(5,4) DEFAULT 0 NOT NULL, parent_confidence DECIMAL(5,4) DEFAULT 0 NOT NULL, "
                    + "indexable_reason VARCHAR(64) DEFAULT '' NOT NULL, "
                    + "metadata_json CLOB, created_time TIMESTAMP(3) NOT NULL)");
        } catch (SQLException ex) {
            throw new IllegalStateException("Unable to apply structured chunking test schema", ex);
        }
    }
}
