package ai.nomoclaw.bot.scheduler.config;

import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

@Component
public class CronSubscriptionSchemaInitializer {

    private final DataSource dataSource;

    public CronSubscriptionSchemaInitializer(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @PostConstruct
    public void initializeIfNeeded() {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS agent_cron_subscription (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        subscription_uid VARCHAR(64) NOT NULL DEFAULT '',
                        job_uid VARCHAR(64) NOT NULL DEFAULT '',
                        channel VARCHAR(32) NOT NULL DEFAULT '',
                        target VARCHAR(1024) NOT NULL DEFAULT '',
                        enabled TINYINT NOT NULL DEFAULT 1,
                        created_time TIMESTAMP(3) NOT NULL,
                        updated_time TIMESTAMP(3) NOT NULL,
                        PRIMARY KEY (id),
                        UNIQUE (subscription_uid),
                        UNIQUE (job_uid, channel, target)
                    """);
            statement.execute("""
                    CREATE INDEX IF NOT EXISTS idx_agent_cron_subscription_job_enabled
                    ON agent_cron_subscription (job_uid, enabled)
                    """);
        } catch (Exception ex) {
            throw new IllegalStateException("failed to initialize agent_cron_subscription schema", ex);
        }
    }
}
