<script setup lang="ts">
import { computed, h, onMounted, ref } from "vue";
import { NButton, NDataTable, NDatePicker, NInput, NSelect } from "naive-ui";
import type { DataTableColumns } from "naive-ui";
import { useRouter } from "vue-router";
import DirectoryRail from "@/components/chat/DirectoryRail.vue";
import AppPageHeader from "@/components/layout/AppPageHeader.vue";
import AppPaginationBar from "@/components/layout/AppPaginationBar.vue";
import { tokenUsageApi } from "@/api/tokenUsageApi";
import type { TokenUsageBreakdown, TokenUsageOverview, TokenUsageRecord } from "@/types/api";

const router = useRouter();
const period = ref("30"); const scene = ref(""); const provider = ref(""); const model = ref(""); const customRange = ref<[number, number] | null>(null); const page = ref(1); const pageSize = ref(20);
const overview = ref<TokenUsageOverview | null>(null); const records = ref<TokenUsageRecord[]>([]); const total = ref(0); const loading = ref(false);
const sceneOptions = [{ label: "全部场景", value: "" }, { label: "聊天推理", value: "CHAT_REASONING" }, { label: "聊天总结", value: "CHAT_SUMMARY" }, { label: "锦囊总结", value: "TIP_SUMMARY" }];
const sceneLabels: Record<string, string> = { CHAT: "聊天", CHAT_REASONING: "聊天推理", CHAT_SUMMARY: "聊天总结", TIP_SUMMARY: "锦囊总结" };
const chartColors = ["#0f766e", "#2f6fed", "#c06a2b", "#8b5cf6", "#d946ef"];
const filter = computed(() => ({ from: customRange.value ? new Date(customRange.value[0]).toISOString().slice(0, 10) : new Date(Date.now() - (Number(period.value) - 1) * 86400000).toISOString().slice(0, 10), to: customRange.value ? new Date(customRange.value[1]).toISOString().slice(0, 10) : "", scene: scene.value, provider: provider.value.trim(), model: model.value.trim() }));
const modelRows = computed(() => sortedRows(overview.value?.byModel ?? []).slice(0, 7));
const sceneRows = computed(() => sortedRows(overview.value?.byScene ?? []));
const dayRows = computed(() => [...(overview.value?.byDay ?? [])].sort((a, b) => a.key.localeCompare(b.key)));
const maxModelTokens = computed(() => Math.max(...modelRows.value.map(item => item.totalTokens), 1));
const maxDayTokens = computed(() => Math.max(...dayRows.value.map(item => item.totalTokens), 1));
const sceneGradient = computed(() => { let start = 0; const stops = sceneRows.value.map((item, index) => { const end = start + (item.totalTokens / Math.max(overview.value?.totalTokens ?? 1, 1)) * 100; const stop = `${chartColors[index % chartColors.length]} ${start.toFixed(1)}% ${end.toFixed(1)}%`; start = end; return stop; }); return stops.length ? `conic-gradient(${stops.join(", ")})` : "none"; });
function sortedRows(rows: TokenUsageBreakdown[]) { return [...rows].sort((a, b) => b.totalTokens - a.totalTokens); }
function shortNumber(value: number) { if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M`; if (value >= 1000) return `${(value / 1000).toFixed(value >= 100000 ? 0 : 1)}k`; return value.toLocaleString(); }
function dayLabel(value: string) { return value.slice(5).replace("-", "/"); }
function tokenValue(row: TokenUsageRecord, value: number | undefined) { return row.usageAvailable ? (value ?? 0).toLocaleString() : "—"; }
function detailRow(label: string, value: string) { return h("div", { class: "usage-detail-row" }, [h("span", label), h("strong", value)]); }
function renderExpand(row: TokenUsageRecord) { const supportsReasoning = row.provider.toLowerCase().includes("codex"); return h("div", { class: "usage-detail-panel" }, [h("div", { class: "usage-detail-group" }, [h("div", { class: "usage-detail-group-title" }, "输入明细"), detailRow("输入 Token", tokenValue(row, row.inputTokens)), detailRow("缓存输入", tokenValue(row, row.cachedInputTokens))]), h("div", { class: "usage-detail-group" }, [h("div", { class: "usage-detail-group-title" }, "输出明细"), detailRow("输出 Token", tokenValue(row, row.outputTokens)), detailRow("推理 Token", supportsReasoning ? tokenValue(row, row.reasoningTokens) : "—")])]); }
const columns = computed<DataTableColumns<TokenUsageRecord>>(() => [{ type: "expand", expandable: row => row.usageAvailable, renderExpand }, { title: "时间", key: "occurredTime", width: 175 }, { title: "场景", key: "scene", width: 130, render: row => sceneLabels[row.scene] ?? row.scene }, { title: "模型", key: "modelName", render: row => `${row.provider}/${row.modelName}` }, { title: "总 Token", key: "totalTokens", width: 100, render: row => tokenValue(row, row.totalTokens) }, { title: "状态", key: "usageAvailable", width: 100, render: row => row.usageAvailable ? "已记录" : "未知" }]);
async function load() { loading.value = true; try { const [summary, result] = await Promise.all([tokenUsageApi.overview(filter.value), tokenUsageApi.page(filter.value, page.value, pageSize.value)]); overview.value = summary; records.value = result.items; total.value = result.total; } finally { loading.value = false; } }
function changeFilter() { page.value = 1; void load(); }
function openRecord(row: TokenUsageRecord) { if (row.conversationUid) void router.push({ path: "/", query: { conversationUid: row.conversationUid } }); }
onMounted(() => void load());
</script>

<template>
  <div class="page-frame app-page-shell"><div class="app-layout app-layout-responsive"><DirectoryRail /><main class="app-main-content"><div class="app-page-content token-usage-page">
    <AppPageHeader title="Token 用量" subtitle="聊天与锦囊总结的模型 token 消耗" />
    <section class="surface-card usage-filter"><div class="filter-group"><span class="filter-label">时间范围</span><n-select v-model:value="period" :options="[{label:'今天',value:'1'},{label:'最近 7 天',value:'7'},{label:'最近 30 天',value:'30'}]" @update:value="() => { customRange = null; changeFilter(); }" /></div><n-date-picker v-model:value="customRange" type="daterange" clearable @update:value="changeFilter" /><n-select v-model:value="scene" :options="sceneOptions" @update:value="changeFilter" /><n-input v-model:value="provider" placeholder="Provider" clearable @keyup.enter="changeFilter" /><n-input v-model:value="model" placeholder="模型" clearable @keyup.enter="changeFilter" /><n-button tertiary :loading="loading" @click="load">刷新</n-button></section>
    <template v-if="overview">
      <section class="usage-stat-grid"><div class="surface-card usage-stat-card usage-stat-card-primary"><div class="stat-heading"><span class="stat-dot" />总 Token</div><strong>{{ overview.totalTokens.toLocaleString() }}</strong><span class="stat-caption">{{ overview.invocationCount.toLocaleString() }} 次调用</span></div><div class="surface-card usage-stat-card"><div class="stat-heading">输入 Token</div><strong>{{ overview.inputTokens.toLocaleString() }}</strong><span class="stat-caption">含缓存输入 {{ overview.cachedInputTokens.toLocaleString() }}</span></div><div class="surface-card usage-stat-card"><div class="stat-heading">输出 Token</div><strong>{{ overview.outputTokens.toLocaleString() }}</strong><span class="stat-caption">模型生成内容</span></div><div class="surface-card usage-stat-card"><div class="stat-heading">未返回用量</div><strong>{{ overview.unavailableUsageCount.toLocaleString() }}</strong><span class="stat-caption">次调用没有用量明细</span></div></section>
      <section class="usage-chart-grid"><div class="surface-card usage-chart-card usage-model-card"><div class="card-heading"><div><div class="surface-card-title">按模型</div><p>Token 消耗最多的模型</p></div><span class="chart-unit">TOKENS</span></div><div v-if="modelRows.length" class="model-bars"><div v-for="(item, index) in modelRows" :key="item.key" class="model-bar-row"><div class="model-bar-label" :title="item.key">{{ item.key }}</div><div class="model-bar-track"><span :style="{ width: `${(item.totalTokens / maxModelTokens) * 100}%`, background: chartColors[index % chartColors.length] }" /></div><strong>{{ shortNumber(item.totalTokens) }}</strong></div></div><div v-else class="empty-chart">暂无数据</div></div>
        <div class="surface-card usage-chart-card usage-scene-card"><div class="card-heading"><div><div class="surface-card-title">按场景</div><p>不同工作流的用量分布</p></div><span class="chart-unit">SHARE</span></div><div class="scene-content"><div class="scene-donut" :style="{ background: sceneGradient }"><div><strong>{{ shortNumber(overview.totalTokens) }}</strong><span>总 Token</span></div></div><div class="scene-legend"><div v-for="(item, index) in sceneRows" :key="item.key" class="scene-legend-row"><span class="legend-swatch" :style="{ background: chartColors[index % chartColors.length] }" /><span>{{ sceneLabels[item.key] ?? item.key }}</span><strong>{{ Math.round(item.totalTokens / Math.max(overview.totalTokens, 1) * 100) }}%</strong></div></div></div></div></section>
      <section class="surface-card usage-chart-card usage-trend-card"><div class="card-heading"><div><div class="surface-card-title">每日趋势</div><p>按天查看 Token 消耗变化</p></div><span class="chart-unit">TOKENS / DAY</span></div><div v-if="dayRows.length" class="daily-chart-wrap"><div class="daily-axis"><span>{{ shortNumber(maxDayTokens) }}</span><span>{{ shortNumber(maxDayTokens / 2) }}</span><span>0</span></div><svg class="daily-chart" viewBox="0 0 900 230" role="img" aria-label="每日 Token 用量柱状图" preserveAspectRatio="none"><line v-for="line in [30, 115, 200]" :key="line" x1="0" :y1="line" x2="900" :y2="line" class="chart-grid-line" /><g v-for="(item, index) in dayRows" :key="item.key"><title>{{ item.key }} · {{ item.totalTokens.toLocaleString() }} tokens</title><rect :x="index * (900 / dayRows.length) + 5" :y="200 - (item.totalTokens / maxDayTokens) * 170" :width="Math.max(8, 900 / dayRows.length - 10)" :height="(item.totalTokens / maxDayTokens) * 170" rx="5" class="daily-bar" /></g></svg><div class="daily-labels"><span v-for="item in dayRows" :key="item.key">{{ dayLabel(item.key) }}</span></div></div><div v-else class="empty-chart">暂无数据</div></section>
      <p class="usage-hint">输入明细和输出明细属于各自总量的组成部分，不会重复计入总 Token；展开记录可查看 provider 支持的明细。</p>
    </template>
    <section class="surface-card usage-records-card"><div class="card-heading"><div><div class="surface-card-title">调用明细</div><p>{{ total.toLocaleString() }} 条记录</p></div></div><n-data-table :columns="columns" :data="records" :loading="loading" :row-key="row => row.recordUid" :row-props="row => ({ onClick: () => openRecord(row) })" /><AppPaginationBar :page="page" :page-size="pageSize" :total="total" @update:page="value => { page = value; load(); }" @update:page-size="value => { pageSize = value; changeFilter(); }" /></section>
  </div></main></div></div>
</template>

<style scoped>
.token-usage-page { gap: var(--space-4); }
.usage-filter { display: flex; gap: var(--space-3); align-items: flex-end; flex-wrap: wrap; padding: var(--space-4); }
.filter-group { display: flex; flex-direction: column; gap: var(--space-1_5); }.filter-label, .chart-unit, .stat-caption { color: var(--color-text-muted); font-size: var(--text-caption-size); }
.usage-filter :deep(.n-select), .usage-filter :deep(> .n-input) { width: 160px; }.usage-filter :deep(.n-date-picker) { width: var(--size-280); }.usage-filter :deep(.n-date-picker .n-input) { width: 100%; }
.usage-stat-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: var(--space-3); }.usage-stat-card { position: relative; min-height: 108px; padding: var(--space-4); display: flex; flex-direction: column; justify-content: space-between; overflow: hidden; }.usage-stat-card::after { content: ""; position: absolute; right: -24px; bottom: -32px; width: 88px; height: 88px; border-radius: 50%; background: var(--stat-accent, var(--color-accent-brand)); opacity: .08; }.usage-stat-card strong { display: block; margin-top: var(--space-2); color: var(--color-text-heading); font-size: clamp(1.35rem, 2vw, 1.75rem); line-height: 1.1; letter-spacing: -0.03em; }.usage-stat-card-primary { --stat-accent: var(--color-accent-brand); border-color: color-mix(in srgb, var(--color-accent-brand) 35%, var(--color-border-soft)); background: linear-gradient(135deg, color-mix(in srgb, var(--color-bg-brand-soft) 70%, var(--color-bg-surface)), var(--color-bg-surface)); }.usage-stat-card:nth-child(2) { --stat-accent: #2f6fed; }.usage-stat-card:nth-child(3) { --stat-accent: #c06a2b; }.usage-stat-card:nth-child(4) { --stat-accent: #8b5cf6; }.stat-heading { display: flex; align-items: center; gap: var(--space-2); color: var(--color-text-secondary); font-size: var(--text-body-size); }.stat-dot { width: 8px; height: 8px; border-radius: 50%; background: var(--stat-accent, var(--color-accent-brand)); box-shadow: 0 0 0 4px color-mix(in srgb, var(--stat-accent, var(--color-accent-brand)) 16%, transparent); }
.usage-chart-grid { display: grid; grid-template-columns: 1.3fr 1fr; gap: var(--space-3); }.usage-chart-card { min-width: 0; padding: var(--space-5); }.card-heading { display: flex; justify-content: space-between; gap: var(--space-4); align-items: flex-start; margin-bottom: var(--space-5); }.card-heading p { margin: var(--space-1) 0 0; color: var(--color-text-muted); font-size: var(--text-caption-size); }.chart-unit { padding-top: 4px; font-family: var(--font-mono); font-size: 10px; letter-spacing: .08em; }
.model-bars { display: flex; flex-direction: column; gap: var(--space-3_5); }.model-bar-row { display: grid; grid-template-columns: minmax(130px, 1.2fr) 2fr 52px; gap: var(--space-3); align-items: center; }.model-bar-label { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--color-text-secondary); font-size: var(--text-caption-size); }.model-bar-track { height: 9px; overflow: hidden; border-radius: var(--radius-pill); background: var(--color-bg-soft-hover); }.model-bar-track span { display: block; height: 100%; min-width: 6px; border-radius: inherit; transition: width .3s ease; }.model-bar-row strong { text-align: right; color: var(--color-text-heading); font-family: var(--font-mono); font-size: var(--text-caption-size); }
.scene-content { display: flex; align-items: center; justify-content: space-around; gap: var(--space-5); min-height: 185px; }.scene-donut { flex: 0 0 150px; width: 150px; height: 150px; display: grid; place-items: center; border-radius: 50%; }.scene-donut > div { width: 94px; height: 94px; display: flex; flex-direction: column; align-items: center; justify-content: center; border-radius: 50%; background: var(--color-bg-surface); }.scene-donut strong { color: var(--color-text-heading); font-size: 1.1rem; }.scene-donut span { margin-top: 2px; color: var(--color-text-muted); font-size: 11px; }.scene-legend { display: flex; flex: 1; flex-direction: column; gap: var(--space-3); }.scene-legend-row { display: grid; grid-template-columns: 10px 1fr auto; gap: var(--space-2); align-items: center; color: var(--color-text-secondary); font-size: var(--text-caption-size); }.scene-legend-row strong { color: var(--color-text-heading); font-family: var(--font-mono); font-size: 12px; }.legend-swatch { width: 8px; height: 8px; border-radius: 3px; }
.usage-trend-card { padding-bottom: var(--space-4); }.daily-chart-wrap { position: relative; padding-left: 42px; }.daily-axis { position: absolute; top: 0; bottom: 27px; left: 0; display: flex; flex-direction: column; justify-content: space-between; color: var(--color-text-muted); font-family: var(--font-mono); font-size: 10px; }.daily-chart { display: block; width: 100%; height: 230px; overflow: visible; }.chart-grid-line { stroke: var(--color-border-soft); stroke-dasharray: 4 5; }.daily-bar { fill: var(--color-accent-brand); opacity: .82; transition: opacity .2s, fill .2s; }.daily-bar:hover { fill: var(--color-accent-brand-hover); opacity: 1; }.daily-labels { display: grid; grid-template-columns: repeat(auto-fit, minmax(36px, 1fr)); gap: 2px; color: var(--color-text-muted); font-family: var(--font-mono); font-size: 10px; text-align: center; }.daily-labels span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.empty-chart { min-height: 180px; display: grid; place-items: center; color: var(--color-text-muted); }.usage-hint { margin: 0; color: var(--color-text-muted); font-size: var(--text-caption-size); }.usage-records-card { padding-bottom: var(--space-3); }.usage-records-card .card-heading { margin-bottom: var(--space-3); }.usage-records-card :deep(.n-data-table .n-data-table-td) { cursor: pointer; }.usage-detail-panel { display: grid; grid-template-columns: repeat(2, minmax(220px, 1fr)); gap: 28px; padding: 4px 24px 8px; }.usage-detail-group-title { margin-bottom: 8px; color: var(--color-text-secondary); font-size: 13px; font-weight: 600; }.usage-detail-row { display: flex; justify-content: space-between; gap: 24px; padding: 6px 0; border-bottom: 1px solid var(--color-border-soft); }.usage-detail-row span { color: var(--color-text-muted); }
@media (max-width: 900px) { .usage-stat-grid { grid-template-columns: repeat(2, 1fr); } .usage-chart-grid { grid-template-columns: 1fr; } } @media (max-width: 700px) { .usage-filter :deep(.n-date-picker), .usage-filter :deep(.n-select), .usage-filter :deep(> .n-input) { width: 100%; } .usage-stat-grid { grid-template-columns: 1fr; } .scene-content { flex-direction: column; } .usage-detail-panel { grid-template-columns: 1fr; gap: 16px; padding-inline: 8px; } }
</style>
